import { Question } from './types'

export const D1_QUESTIONS: Question[] = [

  // ── FACET 1.1 ENERGY SOURCE ── AG×10 ──────────────────────────
  { question_id:'D1-AG-001', dimension:'D1', facet:'Energy Source', type:'AG',
    text_india:'After a full day with a lot of people, I need time alone to feel like myself again.',
    text_usa:'After a busy day with lots of people, I need time alone to feel like myself again.' },
  { question_id:'D1-AG-002', dimension:'D1', facet:'Energy Source', type:'AG',
    text_india:'I find social gatherings energising, even when they go on for a long time.',
    text_usa:'I find social gatherings energising, even when they go long.' },
  { question_id:'D1-AG-003', dimension:'D1', facet:'Energy Source', type:'AG',
    text_india:'I often feel drained after spending time in large groups, even when I enjoyed myself.',
    text_usa:'I often feel drained after spending time in large groups, even if I had fun.' },
  { question_id:'D1-AG-004', dimension:'D1', facet:'Energy Source', type:'AG',
    text_india:'I could spend an entire weekend alone without feeling lonely or restless.',
    text_usa:'I could spend an entire weekend alone and feel completely content.' },
  { question_id:'D1-AG-005', dimension:'D1', facet:'Energy Source', type:'AG',
    text_india:'The more people around me, the more alive I feel.',
    text_usa:'The more people around me, the more alive and energised I feel.' },
  { question_id:'D1-AG-006', dimension:'D1', facet:'Energy Source', type:'AG',
    text_india:'Even in a group I enjoy, I reach a point where I need to step away and recharge.',
    text_usa:'Even in a group I enjoy, there comes a point where I need to step away.' },
  { question_id:'D1-AG-007', dimension:'D1', facet:'Energy Source', type:'AG',
    text_india:'I find it easy to keep going at a party or gathering long after others seem tired.',
    text_usa:'I find it easy to keep going at a party long after others seem tired.' },
  { question_id:'D1-AG-008', dimension:'D1', facet:'Energy Source', type:'AG',
    text_india:'Too much social time makes me feel empty, even when the company is good.',
    text_usa:'Too much time with others leaves me feeling empty, even when I like the people.' },
  { question_id:'D1-AG-009', dimension:'D1', facet:'Energy Source', type:'AG',
    text_india:'I genuinely look forward to spending time alone after a busy week.',
    text_usa:'I genuinely look forward to alone time after a busy week.' },
  { question_id:'D1-AG-010', dimension:'D1', facet:'Energy Source', type:'AG',
    text_india:'Being around people does not drain me — it fills me up.',
    text_usa:'Being around people fills me up rather than draining me.' },

  // ── FACET 1.2 SOCIAL STYLE ── AG×10 ───────────────────────────
  { question_id:'D1-AG-011', dimension:'D1', facet:'Social Style', type:'AG',
    text_india:'I naturally take the lead in conversations and social situations.',
    text_usa:'I naturally take the lead in conversations and social situations.' },
  { question_id:'D1-AG-012', dimension:'D1', facet:'Social Style', type:'AG',
    text_india:'I prefer listening and observing over being the centre of attention.',
    text_usa:'I prefer listening and observing rather than being the centre of attention.' },
  { question_id:'D1-AG-013', dimension:'D1', facet:'Social Style', type:'AG',
    text_india:'I find it easy to talk to strangers and make new connections quickly.',
    text_usa:'I find it easy to talk to strangers and make new connections quickly.' },
  { question_id:'D1-AG-014', dimension:'D1', facet:'Social Style', type:'AG',
    text_india:'I prefer a small number of deep friendships over a wide circle of acquaintances.',
    text_usa:'I prefer a small number of deep friendships to a wide circle of acquaintances.' },
  { question_id:'D1-AG-015', dimension:'D1', facet:'Social Style', type:'AG',
    text_india:'I enjoy being in the thick of a busy social environment.',
    text_usa:'I enjoy being in the middle of a busy, active social environment.' },
  { question_id:'D1-AG-016', dimension:'D1', facet:'Social Style', type:'AG',
    text_india:'I find large social gatherings exhausting rather than fun.',
    text_usa:'I find large social gatherings more exhausting than enjoyable.' },
  { question_id:'D1-AG-017', dimension:'D1', facet:'Social Style', type:'AG',
    text_india:'I tend to have many different social groups and connections.',
    text_usa:'I tend to have many different social groups and wide-ranging connections.' },
  { question_id:'D1-AG-018', dimension:'D1', facet:'Social Style', type:'AG',
    text_india:'People who know me well would describe me as reserved or private.',
    text_usa:'People who know me well would describe me as reserved or private.' },
  { question_id:'D1-AG-019', dimension:'D1', facet:'Social Style', type:'AG',
    text_india:'I thrive in roles that require frequent interaction with many different people.',
    text_usa:'I thrive in roles that require frequent interaction with many different people.' },
  { question_id:'D1-AG-020', dimension:'D1', facet:'Social Style', type:'AG',
    text_india:'I need significant alone time to function at my best.',
    text_usa:'I need significant time alone to consistently function at my best.' },

  // ── FACET 1.3 EXPRESSIVENESS ── AG×10 ─────────────────────────
  { question_id:'D1-AG-021', dimension:'D1', facet:'Expressiveness', type:'AG',
    text_india:'I find it easy to tell people how I am feeling, even when the emotion is difficult.',
    text_usa:'I find it natural to express how I am feeling, even when it is difficult.' },
  { question_id:'D1-AG-022', dimension:'D1', facet:'Expressiveness', type:'AG',
    text_india:'I tend to keep my emotions to myself, even with people I am close to.',
    text_usa:'I tend to keep my emotions private, even with people I trust.' },
  { question_id:'D1-AG-023', dimension:'D1', facet:'Expressiveness', type:'AG',
    text_india:'People who know me well say I am easy to read emotionally.',
    text_usa:'People who know me well say they can always tell how I am feeling.' },
  { question_id:'D1-AG-024', dimension:'D1', facet:'Expressiveness', type:'AG',
    text_india:'I rarely show frustration or upset on my face, even when I feel it strongly.',
    text_usa:'I rarely let frustration show on my face, even when I feel it strongly.' },
  { question_id:'D1-AG-025', dimension:'D1', facet:'Expressiveness', type:'AG',
    text_india:'I am comfortable showing strong emotion — even tears — in front of others.',
    text_usa:'I am comfortable showing strong emotions — even tears — in front of others.' },
  { question_id:'D1-AG-026', dimension:'D1', facet:'Expressiveness', type:'AG',
    text_india:'I feel uncomfortable when people around me become very emotional.',
    text_usa:'I feel uncomfortable when conversations become highly emotional.' },
  { question_id:'D1-AG-027', dimension:'D1', facet:'Expressiveness', type:'AG',
    text_india:'I express enthusiasm and excitement openly and naturally.',
    text_usa:'I express enthusiasm and excitement openly and without much effort.' },
  { question_id:'D1-AG-028', dimension:'D1', facet:'Expressiveness', type:'AG',
    text_india:'I prefer to process difficult feelings alone before talking about them.',
    text_usa:'I prefer to work through difficult feelings alone before sharing them.' },
  { question_id:'D1-AG-029', dimension:'D1', facet:'Expressiveness', type:'AG',
    text_india:'People often comment that I am very expressive or animated.',
    text_usa:'People often tell me I am expressive or animated.' },
  { question_id:'D1-AG-030', dimension:'D1', facet:'Expressiveness', type:'AG',
    text_india:'Even in arguments, I stay calm and controlled on the outside.',
    text_usa:'Even in arguments, I appear calm and controlled on the outside.' },

  // ── FACET 1.4 CONFIDENCE ── AG×10 ─────────────────────────────
  { question_id:'D1-AG-031', dimension:'D1', facet:'Confidence', type:'AG',
    text_india:'I feel comfortable speaking up in a group, even when my view differs from everyone else\'s.',
    text_usa:'I feel comfortable speaking up in a group even when I am the only dissenting voice.' },
  { question_id:'D1-AG-032', dimension:'D1', facet:'Confidence', type:'AG',
    text_india:'I often worry about what others think of me.',
    text_usa:'I often find myself worrying about what other people think of me.' },
  { question_id:'D1-AG-033', dimension:'D1', facet:'Confidence', type:'AG',
    text_india:'I find it easy to introduce myself to strangers and start a conversation.',
    text_usa:'I find it easy to walk up to strangers and start a conversation.' },
  { question_id:'D1-AG-034', dimension:'D1', facet:'Confidence', type:'AG',
    text_india:'I sometimes hold back my opinion because I am not sure it will be well received.',
    text_usa:'I sometimes hold back my opinion because I am not sure how it will land.' },
  { question_id:'D1-AG-035', dimension:'D1', facet:'Confidence', type:'AG',
    text_india:'I feel confident being the centre of attention when the situation calls for it.',
    text_usa:'I feel at ease when I am the centre of attention.' },
  { question_id:'D1-AG-036', dimension:'D1', facet:'Confidence', type:'AG',
    text_india:'I find it hard to take criticism without it affecting my mood for a while.',
    text_usa:'Criticism affects my mood for longer than I would like.' },
  { question_id:'D1-AG-037', dimension:'D1', facet:'Confidence', type:'AG',
    text_india:'I trust my own judgment, even when others around me disagree.',
    text_usa:'I trust my own judgment even when the people around me disagree.' },
  { question_id:'D1-AG-038', dimension:'D1', facet:'Confidence', type:'AG',
    text_india:'I feel anxious or self-conscious in situations where I am being evaluated or observed.',
    text_usa:'I feel anxious or self-conscious when I am being evaluated or watched.' },
  { question_id:'D1-AG-039', dimension:'D1', facet:'Confidence', type:'AG',
    text_india:'I am comfortable disagreeing with people who have more authority than me.',
    text_usa:'I am comfortable respectfully disagreeing with people who have more authority.' },
  { question_id:'D1-AG-040', dimension:'D1', facet:'Confidence', type:'AG',
    text_india:'I generally feel good about who I am and how I come across to others.',
    text_usa:'I generally feel confident about who I am and how I come across to others.' },

  // ── TC×6 ───────────────────────────────────────────────────────
  { question_id:'D1-TC-001', dimension:'D1', facet:'Energy Source', type:'TC',
    text_india:'Which sounds better right now?',
    text_usa:'Which sounds better right now?',
    options_india:[{id:'A',text:'A quiet evening alone at home'},{id:'B',text:'An evening out with a group of people'}],
    options_usa:[{id:'A',text:'A quiet evening alone at home'},{id:'B',text:'Going out with friends or colleagues'}] },
  { question_id:'D1-TC-002', dimension:'D1', facet:'Energy Source', type:'TC',
    text_india:'Which would you genuinely prefer?',
    text_usa:'Which would you genuinely prefer?',
    options_india:[{id:'A',text:'One deep conversation with a close friend'},{id:'B',text:'A lively group dinner with many people'}],
    options_usa:[{id:'A',text:'One meaningful conversation with a close friend'},{id:'B',text:'A lively group dinner with many people'}] },
  { question_id:'D1-TC-003', dimension:'D1', facet:'Social Style', type:'TC',
    text_india:'In a group conversation, which feels more like you?',
    text_usa:'In a group conversation, which feels more like you?',
    options_india:[{id:'A',text:'Being the one who keeps the conversation going'},{id:'B',text:'Being the one who listens and observes'}],
    options_usa:[{id:'A',text:'Being the person who drives the conversation'},{id:'B',text:'Being the one who listens and observes'}] },
  { question_id:'D1-TC-004', dimension:'D1', facet:'Social Style', type:'TC',
    text_india:'Which working environment suits you better?',
    text_usa:'Which working environment suits you better?',
    options_india:[{id:'A',text:'Working from home alone all day'},{id:'B',text:'Working in a busy office with colleagues around'}],
    options_usa:[{id:'A',text:'Working from home alone'},{id:'B',text:'Working in a buzzing office with people around'}] },
  { question_id:'D1-TC-005', dimension:'D1', facet:'Social Style', type:'TC',
    text_india:'Which feels more like you?',
    text_usa:'Which feels more like you?',
    options_india:[{id:'A',text:'Having a small group of very close friends'},{id:'B',text:'Having a wide circle of many friends'}],
    options_usa:[{id:'A',text:'A small circle of close friends'},{id:'B',text:'A wide network of many friends and acquaintances'}] },
  { question_id:'D1-TC-006', dimension:'D1', facet:'Expressiveness', type:'TC',
    text_india:'When someone upsets you:',
    text_usa:'When someone upsets you:',
    options_india:[{id:'A',text:'Tell them directly that you are upset'},{id:'B',text:'Say nothing and deal with it internally'}],
    options_usa:[{id:'A',text:'Tell them directly that you are upset'},{id:'B',text:'Say nothing and deal with it yourself'}] },

  // ── SC×6 ───────────────────────────────────────────────────────
  { question_id:'D1-SC-001', dimension:'D1', facet:'Energy Source', type:'SC',
    text_india:"You have finished your board exams. Your friends want to celebrate with a big group dinner. You are exhausted. What do you do?",
    text_usa:"You just wrapped up a major project. Your team wants to celebrate with a group dinner. You are exhausted. What do you do?",
    options_india:[{id:'A',text:'Go and stay as long as everyone else'},{id:'B',text:'Go but leave early'},{id:'C',text:'Suggest a smaller plan with just 2-3 people'},{id:'D',text:'Skip it — you need to rest'}],
    options_usa:[{id:'A',text:'Go and stay as long as everyone else'},{id:'B',text:'Go but leave early'},{id:'C',text:'Suggest a smaller plan with 2-3 people'},{id:'D',text:'Skip it — you need rest'}] },
  { question_id:'D1-SC-002', dimension:'D1', facet:'Social Style', type:'SC',
    text_india:"You are at a family wedding and you know very few people. What do you honestly do?",
    text_usa:"You are at a work conference and you know almost no one. What do you honestly do?",
    options_india:[{id:'A',text:'Work the room — introduce yourself to as many people as possible'},{id:'B',text:'Find one or two interesting people and stay with them'},{id:'C',text:'Stick close to the people you came with'},{id:'D',text:'Find a quiet corner and wait until you need to be somewhere'}],
    options_usa:[{id:'A',text:'Work the room and introduce yourself to as many as you can'},{id:'B',text:'Find one or two interesting people and have real conversations'},{id:'C',text:'Stay near the colleagues you came with'},{id:'D',text:'Find a quiet spot and engage only when necessary'}] },
  { question_id:'D1-SC-003', dimension:'D1', facet:'Adaptability', type:'SC',
    text_india:"You are starting at a new school or college. First week — what feels most natural?",
    text_usa:"You are starting a new job. Your first week — what feels most natural?",
    options_india:[{id:'A',text:'Getting to know as many people as possible right away'},{id:'B',text:'Observing first and choosing carefully who to connect with'},{id:'C',text:'Focusing on work and letting friendships form naturally'},{id:'D',text:'Feeling a bit lost until you find your people'}],
    options_usa:[{id:'A',text:'Proactively meeting everyone on the team'},{id:'B',text:'Observing first and connecting with those who interest you'},{id:'C',text:'Focusing on the work and letting relationships develop'},{id:'D',text:'Feeling unsettled until you find your place'}] },
  { question_id:'D1-SC-004', dimension:'D1', facet:'Confidence', type:'SC',
    text_india:"You have to present a project alone in front of your entire class. How do you feel the night before?",
    text_usa:"You have to present your work to the whole company. How do you feel the night before?",
    options_india:[{id:'A',text:'Excited — you like being in front of people'},{id:'B',text:'Nervous but it motivates you to prepare well'},{id:'C',text:'Anxious — the public speaking part worries you'},{id:'D',text:'Dreading it — you wish someone else could do it'}],
    options_usa:[{id:'A',text:'Genuinely looking forward to it'},{id:'B',text:'Nervous but it pushes you to prepare well'},{id:'C',text:'Anxious about the visibility'},{id:'D',text:'Dreading it and wishing someone else could do it'}] },
  { question_id:'D1-SC-005', dimension:'D1', facet:'Expressiveness', type:'SC',
    text_india:"A close friend tells you something that deeply upsets you. What do you do?",
    text_usa:"A close colleague says something that genuinely upsets you. What do you do?",
    options_india:[{id:'A',text:'Tell them honestly that it has hurt you'},{id:'B',text:'Show that you are upset without saying it directly'},{id:'C',text:'Process it alone first — bring it up later or not at all'},{id:'D',text:'Act like it is fine even though it is not'}],
    options_usa:[{id:'A',text:'Tell them directly and honestly'},{id:'B',text:'Let them see you are upset without spelling it out'},{id:'C',text:'Process it alone — you may or may not raise it later'},{id:'D',text:'Keep it to yourself and act like nothing happened'}] },
  { question_id:'D1-SC-006', dimension:'D1', facet:'Energy Source', type:'SC',
    text_india:"Free Sunday. No plans. No obligations. What does your ideal day look like?",
    text_usa:"A rare completely free day. No work, no obligations. What does your ideal day look like?",
    options_india:[{id:'A',text:'Calling friends and making plans to go out'},{id:'B',text:'A mix — some time alone and some time with people'},{id:'C',text:'Mostly at home — reading, watching something, doing your own thing'},{id:'D',text:'Completely alone — people are exhausting sometimes'}],
    options_usa:[{id:'A',text:'Making plans — going out, seeing people'},{id:'B',text:'A mix of solo time and catching up with someone'},{id:'C',text:'Mostly alone — pursuing something you enjoy'},{id:'D',text:'Completely alone — you need it'}] },

  // ── IP×5 ───────────────────────────────────────────────────────
  { question_id:'D1-IP-001', dimension:'D1', facet:'Energy Source', type:'IP', timer_seconds:8,
    text_india:'Which sounds better right now — no thinking?',
    text_usa:'Which sounds better right now — no thinking?',
    options_india:[{id:'A',text:'Big family gathering'},{id:'B',text:'Evening alone with a book'}],
    options_usa:[{id:'A',text:'Large party'},{id:'B',text:'Quiet evening alone'}] },
  { question_id:'D1-IP-002', dimension:'D1', facet:'Social Style', type:'IP', timer_seconds:8,
    text_india:'Meeting someone new. Your instinct?',
    text_usa:'Meeting someone new. Your instinct?',
    options_india:[{id:'A',text:'Make the first move and introduce yourself'},{id:'B',text:'Wait to be introduced'}],
    options_usa:[{id:'A',text:'Introduce yourself first'},{id:'B',text:'Wait for others to approach you'}] },
  { question_id:'D1-IP-003', dimension:'D1', facet:'Energy Source', type:'IP', timer_seconds:8,
    text_india:'Work environment — quick pick:',
    text_usa:'Work environment — quick pick:',
    options_india:[{id:'A',text:'Busy open office'},{id:'B',text:'Quiet private workspace'}],
    options_usa:[{id:'A',text:'Busy open office'},{id:'B',text:'Private quiet workspace'}] },
  { question_id:'D1-IP-004', dimension:'D1', facet:'Social Style', type:'IP', timer_seconds:8,
    text_india:'When you need to solve a problem:',
    text_usa:'When you need to solve a problem:',
    options_india:[{id:'A',text:'Talk it through with others'},{id:'B',text:'Think it through alone'}],
    options_usa:[{id:'A',text:'Talk it through'},{id:'B',text:'Think it through alone'}] },
  { question_id:'D1-IP-005', dimension:'D1', facet:'Adaptability', type:'IP', timer_seconds:8,
    text_india:'New environment — your gut reaction:',
    text_usa:'New environment — your gut reaction:',
    options_india:[{id:'A',text:'Jump in and figure it out'},{id:'B',text:'Watch and learn before engaging'}],
    options_usa:[{id:'A',text:'Jump in immediately'},{id:'B',text:'Observe first'}] },

  // ── CS×3 ───────────────────────────────────────────────────────
  { question_id:'D1-CS-001', dimension:'D1', facet:'Energy Source', type:'CS',
    text_india:'The type of social situation that drains me most is...',
    text_usa:'The type of social situation I find most exhausting is...' },
  { question_id:'D1-CS-002', dimension:'D1', facet:'Self-Disclosure', type:'CS',
    text_india:'When I meet someone new, I usually...',
    text_usa:'When I meet someone new, I typically...' },
  { question_id:'D1-CS-003', dimension:'D1', facet:'Social Style', type:'CS',
    text_india:'The version of me that people rarely get to see is...',
    text_usa:'The side of me that most people never see is...' },
]

export default D1_QUESTIONS
