import { Question } from './types'

export const D2_QUESTIONS: Question[] = [

  // ── FACET 2.1 PROBLEM TYPE ── AG×15 ────────────────────────────
  { question_id:'D2-AG-001', dimension:'D2', facet:'Problem Type', type:'AG',
    text_india:'I get genuinely absorbed in problems that do not have a clear right answer.',
    text_usa:'I get genuinely absorbed in problems that have no single right answer.' },
  { question_id:'D2-AG-002', dimension:'D2', facet:'Problem Type', type:'AG',
    text_india:'I enjoy pulling apart how systems work — understanding what drives what.',
    text_usa:'I enjoy understanding how systems work — what drives what, how it all connects.' },
  { question_id:'D2-AG-003', dimension:'D2', facet:'People vs Ideas', type:'AG',
    text_india:'I am drawn to human problems — why people behave the way they do.',
    text_usa:'I am drawn to questions about human behaviour — why people do what they do.' },
  { question_id:'D2-AG-004', dimension:'D2', facet:'Problem Type', type:'AG',
    text_india:'I enjoy working with numbers and data more than with words and ideas.',
    text_usa:'I enjoy working with data and numbers more than words and concepts.' },
  { question_id:'D2-AG-005', dimension:'D2', facet:'Creative vs Analytical', type:'AG',
    text_india:'I find creative challenges — making something that did not exist before — genuinely exciting.',
    text_usa:'I find creative challenges — making something from nothing — genuinely exciting.' },
  { question_id:'D2-AG-006', dimension:'D2', facet:'Problem Type', type:'AG',
    text_india:'I enjoy debates and arguments — working out what is true through reasoning.',
    text_usa:'I enjoy debates and reasoning — working out what is actually true.' },
  { question_id:'D2-AG-007', dimension:'D2', facet:'Depth vs Breadth', type:'AG',
    text_india:'I am more interested in the big picture than in the technical detail of things.',
    text_usa:'I am more drawn to big-picture thinking than to technical detail.' },
  { question_id:'D2-AG-008', dimension:'D2', facet:'Problem Type', type:'AG',
    text_india:'I find it satisfying to fix or improve things that are broken or inefficient.',
    text_usa:'I find real satisfaction in fixing or improving things that are broken.' },
  { question_id:'D2-AG-009', dimension:'D2', facet:'Problem Type', type:'AG',
    text_india:'I am drawn to questions about meaning, ethics, and how life should be lived.',
    text_usa:'I find myself drawn to questions of meaning, ethics, and how to live well.' },
  { question_id:'D2-AG-010', dimension:'D2', facet:'Problem Type', type:'AG',
    text_india:'I like problems with precise, verifiable answers — where you can know when you are right.',
    text_usa:'I prefer problems with clear verifiable answers rather than open-ended ones.' },
  { question_id:'D2-AG-011', dimension:'D2', facet:'Creative vs Analytical', type:'AG',
    text_india:'I am more comfortable with logic and evidence than with instinct and feeling.',
    text_usa:'I am more comfortable working with logic and evidence than instinct and intuition.' },
  { question_id:'D2-AG-012', dimension:'D2', facet:'Learning Drive', type:'AG',
    text_india:'I often read or research things purely out of curiosity, with no practical purpose.',
    text_usa:'I often read or research things purely out of curiosity, with no practical goal.' },
  { question_id:'D2-AG-013', dimension:'D2', facet:'Depth vs Breadth', type:'AG',
    text_india:'I prefer going very deep into one subject I love over knowing a little about many things.',
    text_usa:'I prefer deep expertise in one subject over broad knowledge across many areas.' },
  { question_id:'D2-AG-014', dimension:'D2', facet:'People vs Ideas', type:'AG',
    text_india:'I find working with tangible, physical things more interesting than abstract ideas.',
    text_usa:'I find working with tangible things more interesting than abstract ideas and concepts.' },
  { question_id:'D2-AG-015', dimension:'D2', facet:'Learning Drive', type:'AG',
    text_india:'When I discover something new and fascinating, I want to tell someone about it immediately.',
    text_usa:'When I discover something fascinating, I immediately want to share it with someone.' },

  // ── FACET 2.2 SUBJECT DOMAIN ── AG×15 ─────────────────────────
  { question_id:'D2-AG-016', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'When I read the news, science and technology stories draw my attention most.',
    text_usa:'When I follow the news, science and technology stories draw my attention most.' },
  { question_id:'D2-AG-017', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'I find business, startups and entrepreneurship genuinely fascinating.',
    text_usa:'I find the world of business, startups and entrepreneurship genuinely exciting.' },
  { question_id:'D2-AG-018', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'Art, music, film and literature move me more than most other things.',
    text_usa:'Art, music, film and literature move me more than most other things.' },
  { question_id:'D2-AG-019', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'I care deeply about social issues and the wellbeing of people in society.',
    text_usa:'I care deeply about social issues and the wellbeing of others in the world.' },
  { question_id:'D2-AG-020', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'I find legal, political and governance questions genuinely interesting.',
    text_usa:'I find legal and political questions genuinely interesting — not just important.' },
  { question_id:'D2-AG-021', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'I am drawn to understanding how the economy and financial systems work.',
    text_usa:'I find myself genuinely curious about how financial systems and economies work.' },
  { question_id:'D2-AG-022', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'Questions about health, medicine and the human body fascinate me.',
    text_usa:'Questions about the human body, medicine and health genuinely fascinate me.' },
  { question_id:'D2-AG-023', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'I love the idea of building things — physical objects, software, or structures.',
    text_usa:'I love the idea of building things — whether software, objects or structures.' },
  { question_id:'D2-AG-024', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'I am drawn to performance — sport, music, acting or other forms of live expression.',
    text_usa:'I am drawn to performance — whether sport, music, acting or other live expression.' },
  { question_id:'D2-AG-025', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'Teaching, guiding or mentoring others is something I genuinely enjoy.',
    text_usa:'Teaching or guiding others is something I find genuinely fulfilling.' },
  { question_id:'D2-AG-026', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'I find myself naturally curious about psychology and what makes people tick.',
    text_usa:'I find myself naturally curious about psychology and what motivates people.' },
  { question_id:'D2-AG-027', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'Science and discovery — understanding how the natural world works — genuinely excites me.',
    text_usa:'Science and discovery — understanding how the natural world works — genuinely excites me.' },
  { question_id:'D2-AG-028', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'I am more interested in making things beautiful than making them functional.',
    text_usa:'I am more drawn to making things beautiful than to making them purely functional.' },
  { question_id:'D2-AG-029', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'History, culture and understanding how societies evolved genuinely interests me.',
    text_usa:'History, culture and how societies evolved genuinely interests me.' },
  { question_id:'D2-AG-030', dimension:'D2', facet:'Domain', type:'AG',
    text_india:'I am fascinated by how technology is changing the world.',
    text_usa:'I am genuinely fascinated by how technology is changing the world.' },

  // ── TC×6 ───────────────────────────────────────────────────────
  { question_id:'D2-TC-001', dimension:'D2', facet:'People vs Ideas', type:'TC',
    text_india:'Which pulls you more?',
    text_usa:'Which pulls you more?',
    options_india:[{id:'A',text:'A problem involving people and relationships'},{id:'B',text:'A problem involving systems and logic'}],
    options_usa:[{id:'A',text:'A problem involving people and relationships'},{id:'B',text:'A problem involving systems and data'}] },
  { question_id:'D2-TC-002', dimension:'D2', facet:'Creative vs Analytical', type:'TC',
    text_india:'Which energises you more?',
    text_usa:'Which energises you more?',
    options_india:[{id:'A',text:'Creating something new'},{id:'B',text:'Improving something that already exists'}],
    options_usa:[{id:'A',text:'Creating something original'},{id:'B',text:'Making something existing work better'}] },
  { question_id:'D2-TC-003', dimension:'D2', facet:'Depth vs Breadth', type:'TC',
    text_india:'Which feels more like you?',
    text_usa:'Which feels more like you?',
    options_india:[{id:'A',text:'Go very deep into one subject you love'},{id:'B',text:'Explore broadly across many subjects'}],
    options_usa:[{id:'A',text:'Go very deep into one subject'},{id:'B',text:'Explore broadly across many subjects'}] },
  { question_id:'D2-TC-004', dimension:'D2', facet:'Domain', type:'TC',
    text_india:'Which world interests you more?',
    text_usa:'Which world interests you more?',
    options_india:[{id:'A',text:'Science and technology'},{id:'B',text:'Art and human expression'}],
    options_usa:[{id:'A',text:'Tech and science'},{id:'B',text:'Art and creativity'}] },
  { question_id:'D2-TC-005', dimension:'D2', facet:'Domain', type:'TC',
    text_india:'Which appeals more to you?',
    text_usa:'Which appeals more to you?',
    options_india:[{id:'A',text:'Business and building wealth'},{id:'B',text:'People and social impact'}],
    options_usa:[{id:'A',text:'Business and finance'},{id:'B',text:'People and social good'}] },
  { question_id:'D2-TC-006', dimension:'D2', facet:'Learning Drive', type:'TC',
    text_india:'Why do you learn?',
    text_usa:'Why do you learn?',
    options_india:[{id:'A',text:'Because it genuinely fascinates you'},{id:'B',text:'Because it is useful and will help you achieve something'}],
    options_usa:[{id:'A',text:'Learn for fascination'},{id:'B',text:'Learn for usefulness'}] },

  // ── SC×4 ───────────────────────────────────────────────────────
  { question_id:'D2-SC-001', dimension:'D2', facet:'Domain', type:'SC',
    text_india:"You have a completely free afternoon — access to anything. What do you actually end up doing?",
    text_usa:"You have a free afternoon and no obligations. What do you genuinely end up doing?",
    options_india:[{id:'A',text:'Reading about a topic that genuinely fascinates you'},{id:'B',text:'Working on a creative project you have been putting off'},{id:'C',text:'Trying to understand how something you use actually works'},{id:'D',text:'Nothing specific — it depends on your mood'}],
    options_usa:[{id:'A',text:'Going deep on a topic you find fascinating'},{id:'B',text:'Working on a creative project'},{id:'C',text:'Figuring out how something works'},{id:'D',text:'No fixed pattern — it varies by mood'}] },
  { question_id:'D2-SC-002', dimension:'D2', facet:'Learning Drive', type:'SC',
    text_india:"You read something that completely contradicts what you believed before. What do you do?",
    text_usa:"You encounter an article that directly challenges something you believed to be true. What happens?",
    options_india:[{id:'A',text:'Get genuinely excited and want to explore further'},{id:'B',text:'Consider it carefully and update your view if the evidence is good'},{id:'C',text:'Feel slightly unsettled but note it'},{id:'D',text:'Read it sceptically — you rarely change your mind easily'}],
    options_usa:[{id:'A',text:'Get genuinely interested and want to go deeper'},{id:'B',text:'Consider it carefully and update your view if warranted'},{id:'C',text:'Feel mildly unsettled'},{id:'D',text:'Read it sceptically — you rarely change your mind from a single article'}] },
  { question_id:'D2-SC-003', dimension:'D2', facet:'Domain', type:'SC',
    text_india:"If you could shadow any professional for a week to understand their work, who do you choose?",
    text_usa:"You can spend a week shadowing any professional. Who do you choose?",
    options_india:[{id:'A',text:'A scientist or researcher doing cutting-edge work'},{id:'B',text:'A founder building a company they believe in'},{id:'C',text:'A filmmaker, writer or musician at the top of their craft'},{id:'D',text:'An IAS officer or policy maker shaping society'}],
    options_usa:[{id:'A',text:'A researcher or scientist doing frontier work'},{id:'B',text:'A founder or executive building something significant'},{id:'C',text:'A filmmaker, artist or musician at the peak of their career'},{id:'D',text:'A federal judge, senator, or senior policy official'}] },
  { question_id:'D2-SC-004', dimension:'D2', facet:'Domain', type:'SC',
    text_india:"Designing your ideal career — constraints removed. What must it include?",
    text_usa:"You are designing your ideal career from scratch — no constraints. The one thing it must involve:",
    options_india:[{id:'A',text:'Solving hard technical or scientific problems'},{id:'B',text:'Creating something that did not exist before'},{id:'C',text:'Making a real difference to people\'s lives'},{id:'D',text:'Building wealth and financial freedom'}],
    options_usa:[{id:'A',text:'Solving intellectually hard problems'},{id:'B',text:'Creating something original'},{id:'C',text:'Making a measurable difference in people\'s lives'},{id:'D',text:'Building significant financial success'}] },

  // ── IP×6 ───────────────────────────────────────────────────────
  { question_id:'D2-IP-001', dimension:'D2', facet:'People vs Ideas', type:'IP', timer_seconds:8,
    text_india:'Which pulls you more?',
    text_usa:'Which pulls you more?',
    options_india:[{id:'A',text:'Work with people'},{id:'B',text:'Work with ideas and systems'}],
    options_usa:[{id:'A',text:'Working with people'},{id:'B',text:'Working with ideas and data'}] },
  { question_id:'D2-IP-002', dimension:'D2', facet:'Creative vs Analytical', type:'IP', timer_seconds:8,
    text_india:'Which energises you more?',
    text_usa:'Which energises you more?',
    options_india:[{id:'A',text:'Create something'},{id:'B',text:'Analyse something'}],
    options_usa:[{id:'A',text:'Create something new'},{id:'B',text:'Analyse something existing'}] },
  { question_id:'D2-IP-003', dimension:'D2', facet:'Depth vs Breadth', type:'IP', timer_seconds:8,
    text_india:'For your career:',
    text_usa:'For your career:',
    options_india:[{id:'A',text:'Know one thing deeply'},{id:'B',text:'Know many things broadly'}],
    options_usa:[{id:'A',text:'Deep expertise in one area'},{id:'B',text:'Broad knowledge across many areas'}] },
  { question_id:'D2-IP-004', dimension:'D2', facet:'Domain', type:'IP', timer_seconds:8,
    text_india:'Which problem type attracts you more?',
    text_usa:'Which problem type attracts you more?',
    options_india:[{id:'A',text:'A human problem'},{id:'B',text:'A systems problem'}],
    options_usa:[{id:'A',text:'Human problem'},{id:'B',text:'Systems problem'}] },
  { question_id:'D2-IP-005', dimension:'D2', facet:'Learning Drive', type:'IP', timer_seconds:8,
    text_india:'Why you learn:',
    text_usa:'Why you learn:',
    options_india:[{id:'A',text:'Fascination — you cannot help it'},{id:'B',text:'Purpose — it serves a goal'}],
    options_usa:[{id:'A',text:'Fascination — you cannot help it'},{id:'B',text:'Purpose — it serves a specific goal'}] },
  { question_id:'D2-IP-006', dimension:'D2', facet:'Domain', type:'IP', timer_seconds:8,
    text_india:'Which impact matters more?',
    text_usa:'Which impact matters more?',
    options_india:[{id:'A',text:'Wide impact — work seen by many'},{id:'B',text:'Deep impact — work that matters to a few'}],
    options_usa:[{id:'A',text:'Wide impact'},{id:'B',text:'Deep impact on fewer people'}] },

  // ── CS×4 ───────────────────────────────────────────────────────
  { question_id:'D2-CS-001', dimension:'D2', facet:'Domain', type:'CS',
    text_india:'If marks and money did not matter, I would spend my life working on...',
    text_usa:'If money and status were not factors, I would spend my career working on...' },
  { question_id:'D2-CS-002', dimension:'D2', facet:'Learning Drive', type:'CS',
    text_india:'The subject I could read about for hours without getting bored is...',
    text_usa:'The topic I can go down a rabbit hole on without noticing the time is...' },
  { question_id:'D2-CS-003', dimension:'D2', facet:'Domain', type:'CS',
    text_india:'The career I secretly find most interesting — even if I have never told anyone — is...',
    text_usa:'The field I find most fascinating but have never seriously pursued is...' },
  { question_id:'D2-CS-004', dimension:'D2', facet:'Problem Type', type:'CS',
    text_india:'The question I keep coming back to — the one I cannot stop thinking about — is...',
    text_usa:'The question I keep returning to — the one I cannot stop thinking about — is...' },
]

export default D2_QUESTIONS
