import { Question } from './types'

export const D3_QUESTIONS: Question[] = [

  // ── VERBAL APTITUDE ── AG×15 ────────────────────────────────────
  { question_id:'D3-AG-001', dimension:'D3', facet:'Verbal', type:'AG',
    text_india:'I find it easy to express my ideas clearly in writing.',
    text_usa:'I find it easy to express complex ideas clearly in writing.' },
  { question_id:'D3-AG-002', dimension:'D3', facet:'Verbal', type:'AG',
    text_india:'When reading something complex, I usually grasp the main argument quickly.',
    text_usa:'When I read something complex, I usually understand the core argument quickly.' },
  { question_id:'D3-AG-003', dimension:'D3', facet:'Verbal', type:'AG',
    text_india:'I enjoy debates and can usually hold my own in a good argument.',
    text_usa:'I enjoy a good debate and can hold my position under pressure.' },
  { question_id:'D3-AG-004', dimension:'D3', facet:'Verbal', type:'AG',
    text_india:'I tend to express myself better in writing than in speech.',
    text_usa:'I express myself more clearly in writing than in conversation.' },
  { question_id:'D3-AG-005', dimension:'D3', facet:'Verbal', type:'AG',
    text_india:'I pick up quickly on what people really mean — not just what they say.',
    text_usa:'I quickly pick up on the gap between what people say and what they mean.' },
  { question_id:'D3-AG-006', dimension:'D3', facet:'Verbal', type:'AG',
    text_india:'I find it satisfying to find exactly the right word for something.',
    text_usa:'I find genuine satisfaction in finding exactly the right word.' },
  { question_id:'D3-AG-007', dimension:'D3', facet:'Verbal', type:'AG',
    text_india:'I can usually tell when an argument has a logical flaw, even without naming it.',
    text_usa:'I can usually spot when an argument has a flaw, even if I cannot immediately say what it is.' },
  { question_id:'D3-AG-008', dimension:'D3', facet:'Verbal', type:'AG',
    text_india:'I find storytelling — written, spoken or visual — a natural way to explain things.',
    text_usa:'I find storytelling a natural way to explain things to others.' },
  { question_id:'D3-AG-009', dimension:'D3', facet:'Verbal', type:'AG',
    text_india:'People often say I have a way with words.',
    text_usa:'People often tell me I have a way with words.' },
  { question_id:'D3-AG-010', dimension:'D3', facet:'Verbal', type:'AG',
    text_india:'I read for pleasure and do it regularly.',
    text_usa:'I read for pleasure and do so regularly.' },

  // ── NUMERICAL APTITUDE ── AG×10 ────────────────────────────────
  { question_id:'D3-AG-011', dimension:'D3', facet:'Numerical', type:'AG',
    text_india:'Numbers make intuitive sense to me — I can work with them comfortably in my head.',
    text_usa:'Numbers come naturally to me — I can work with them in my head comfortably.' },
  { question_id:'D3-AG-012', dimension:'D3', facet:'Numerical', type:'AG',
    text_india:'I like finding patterns in data — spotting trends or anomalies before others do.',
    text_usa:'I enjoy finding patterns in data — I often spot trends before others do.' },
  { question_id:'D3-AG-013', dimension:'D3', facet:'Numerical', type:'AG',
    text_india:'I enjoy estimating things mentally — roughly how much, how long, how many.',
    text_usa:'I enjoy doing rough mental calculations — estimates, ratios, sizes.' },
  { question_id:'D3-AG-014', dimension:'D3', facet:'Numerical', type:'AG',
    text_india:'When I see a graph or chart, I immediately start reading and interpreting the data.',
    text_usa:'I naturally start reading and interpreting charts and graphs — they make sense to me quickly.' },
  { question_id:'D3-AG-015', dimension:'D3', facet:'Numerical', type:'AG',
    text_india:'I can spot when a number in a report or conversation does not add up.',
    text_usa:'I notice when a number somewhere does not add up — it stands out to me immediately.' },

  // ── SPATIAL APTITUDE ── AG×10 ───────────────────────────────────
  { question_id:'D3-AG-016', dimension:'D3', facet:'Spatial', type:'AG',
    text_india:'I find it easy to imagine how a 3D object looks from different angles.',
    text_usa:'I can easily visualise how a three-dimensional object looks from different angles.' },
  { question_id:'D3-AG-017', dimension:'D3', facet:'Spatial', type:'AG',
    text_india:'When I look at a map, I can orient myself and understand spatial relationships easily.',
    text_usa:'I find it easy to read maps and understand spatial relationships.' },
  { question_id:'D3-AG-018', dimension:'D3', facet:'Spatial', type:'AG',
    text_india:'I can picture how furniture or objects would look in a room before they are placed.',
    text_usa:'I can picture how objects would fit or look in a space before trying them.' },
  { question_id:'D3-AG-019', dimension:'D3', facet:'Spatial', type:'AG',
    text_india:'I find it easy to assemble things from diagrams — I can see how parts fit together.',
    text_usa:'I find assembly instructions easy to follow — I can see how parts fit together spatially.' },
  { question_id:'D3-AG-020', dimension:'D3', facet:'Spatial', type:'AG',
    text_india:'I prefer diagrams and visuals over written explanations for most things.',
    text_usa:'I understand things faster from a diagram than from a written explanation.' },

  // ── IDEA GENERATION ── AG×10 ────────────────────────────────────
  { question_id:'D3-AG-021', dimension:'D3', facet:'Idea Generation', type:'AG',
    text_india:'I often make connections between things that others do not see as related.',
    text_usa:'I frequently make connections between ideas that others do not see as related.' },
  { question_id:'D3-AG-022', dimension:'D3', facet:'Idea Generation', type:'AG',
    text_india:'I often have more ideas than I have time to develop.',
    text_usa:'I generate more ideas than I can ever act on.' },
  { question_id:'D3-AG-023', dimension:'D3', facet:'Idea Generation', type:'AG',
    text_india:'I enjoy brainstorming and the early creative phase more than execution.',
    text_usa:'I enjoy the ideation and creative phase of a project more than the execution.' },
  { question_id:'D3-AG-024', dimension:'D3', facet:'Idea Generation', type:'AG',
    text_india:'I am comfortable starting with a vague brief and working out the direction as I go.',
    text_usa:'I am comfortable with vague starting points — I find my way as I go.' },
  { question_id:'D3-AG-025', dimension:'D3', facet:'Idea Generation', type:'AG',
    text_india:'My best ideas come unexpectedly — in the shower, on a walk, just before sleep.',
    text_usa:'My best ideas tend to come unexpectedly rather than through deliberate effort.' },

  // ── SYSTEMATIC THINKING ── AG×10 ───────────────────────────────
  { question_id:'D3-AG-026', dimension:'D3', facet:'Systematic', type:'AG',
    text_india:'I like having a clear system or method for doing things — structure helps me work better.',
    text_usa:'I work better when I have a clear system or method — structure helps me.' },
  { question_id:'D3-AG-027', dimension:'D3', facet:'Systematic', type:'AG',
    text_india:'I naturally create checklists, processes or frameworks when approaching a problem.',
    text_usa:'I naturally build frameworks or processes when approaching problems.' },
  { question_id:'D3-AG-028', dimension:'D3', facet:'Systematic', type:'AG',
    text_india:'I find satisfaction in creating order out of complexity.',
    text_usa:'Creating order from complexity genuinely satisfies me.' },
  { question_id:'D3-AG-029', dimension:'D3', facet:'Systematic', type:'AG',
    text_india:'I prefer to fully understand a process before starting it.',
    text_usa:'I prefer to fully understand a process before I begin.' },
  { question_id:'D3-AG-030', dimension:'D3', facet:'Systematic', type:'AG',
    text_india:'I find it satisfying when a plan comes together exactly as designed.',
    text_usa:'I find real satisfaction when a plan executes exactly as I designed it.' },

  // ── TC×5 ───────────────────────────────────────────────────────
  { question_id:'D3-TC-001', dimension:'D3', facet:'Verbal vs Numerical', type:'TC',
    text_india:'Which feels more natural?',
    text_usa:'Which feels more natural?',
    options_india:[{id:'A',text:'Explain a complex idea in words'},{id:'B',text:'Represent it with numbers and data'}],
    options_usa:[{id:'A',text:'Explain it in words'},{id:'B',text:'Show it in numbers and data'}] },
  { question_id:'D3-TC-002', dimension:'D3', facet:'Verbal vs Spatial', type:'TC',
    text_india:'Which do you prefer?',
    text_usa:'Which do you prefer?',
    options_india:[{id:'A',text:'Write about something'},{id:'B',text:'Draw or diagram it'}],
    options_usa:[{id:'A',text:'Write about it'},{id:'B',text:'Draw or diagram it'}] },
  { question_id:'D3-TC-003', dimension:'D3', facet:'Idea Generation vs Systematic', type:'TC',
    text_india:'Which suits you better?',
    text_usa:'Which suits you better?',
    options_india:[{id:'A',text:'Generate many ideas — explore widely first'},{id:'B',text:'Build a clear framework — organise before you explore'}],
    options_usa:[{id:'A',text:'Generate many ideas — explore widely first'},{id:'B',text:'Build a clear framework — organise before exploring'}] },
  { question_id:'D3-TC-004', dimension:'D3', facet:'Numerical vs Spatial', type:'TC',
    text_india:'Which comes more naturally?',
    text_usa:'Which comes more naturally?',
    options_india:[{id:'A',text:'Mental arithmetic — working with numbers in your head'},{id:'B',text:'Mental visualisation — picturing objects and spaces'}],
    options_usa:[{id:'A',text:'Mental arithmetic — working with numbers'},{id:'B',text:'Mental visualisation — picturing objects and spaces'}] },
  { question_id:'D3-TC-005', dimension:'D3', facet:'Verbal vs Analytical', type:'TC',
    text_india:'When helping someone understand something:',
    text_usa:'When helping someone understand something:',
    options_india:[{id:'A',text:'You naturally find the right story or analogy'},{id:'B',text:'You naturally build the logical argument step by step'}],
    options_usa:[{id:'A',text:'You naturally find the right story or analogy'},{id:'B',text:'You naturally build the logical argument step by step'}] },

  // ── SC×4 ───────────────────────────────────────────────────────
  { question_id:'D3-SC-001', dimension:'D3', facet:'Natural Aptitude', type:'SC',
    text_india:"Your group has to present a project. Dividing tasks — which part do you take?",
    text_usa:"Your team needs to produce a report. Splitting the work — which part do you volunteer for?",
    options_india:[{id:'A',text:'Writing and structuring the main content'},{id:'B',text:'Designing the visuals and layout'},{id:'C',text:'Doing the research and finding the data'},{id:'D',text:'Presenting and speaking to the audience'}],
    options_usa:[{id:'A',text:'Writing and structuring the core content'},{id:'B',text:'Designing the visuals and presentation'},{id:'C',text:'Researching and gathering the data'},{id:'D',text:'Presenting it to stakeholders'}] },
  { question_id:'D3-SC-002', dimension:'D3', facet:'Verbal', type:'SC',
    text_india:"A friend needs to write a difficult message — to a parent, a teacher, someone they hurt. You?",
    text_usa:"A colleague needs to write a difficult message to a senior leader. You?",
    options_india:[{id:'A',text:'Help them find the right words — this is something you are good at'},{id:'B',text:'Help them think through what to say but leave the writing to them'},{id:'C',text:'Suggest they just be direct and not overthink it'},{id:'D',text:'This is not something you feel well-placed to help with'}],
    options_usa:[{id:'A',text:'Help them get the words right — this is something you are good at'},{id:'B',text:'Help them think through what to say but leave the writing to them'},{id:'C',text:'Tell them to keep it simple and just say it directly'},{id:'D',text:'You are not the right person to help with this'}] },
  { question_id:'D3-SC-003', dimension:'D3', facet:'Systematic', type:'SC',
    text_india:"You are given a complex project with no clear structure or process. What do you do first?",
    text_usa:"You are given a complex project with no clear structure or process. What do you do first?",
    options_india:[{id:'A',text:'Create a framework — define the phases, tasks, and timeline'},{id:'B',text:'Start working — structure will emerge as you go'},{id:'C',text:'Research how others have done similar things first'},{id:'D',text:'Talk it through with someone to figure out the shape'}],
    options_usa:[{id:'A',text:'Create a framework — define the phases, tasks, and timeline'},{id:'B',text:'Start working — structure will emerge as you go'},{id:'C',text:'Research how others have approached similar problems'},{id:'D',text:'Talk it through with someone to figure out the shape'}] },
  { question_id:'D3-SC-004', dimension:'D3', facet:'Natural Aptitude', type:'SC',
    text_india:"Someone asks you to explain a difficult concept to a much younger cousin. What do you do?",
    text_usa:"You need to explain a technical concept to a non-technical colleague. What do you do?",
    options_india:[{id:'A',text:'Find the right analogy or story — this is enjoyable for you'},{id:'B',text:'Walk through it carefully step by step'},{id:'C',text:'Draw a diagram or use a visual'},{id:'D',text:'Find it difficult — simplifying your own knowledge is genuinely hard'}],
    options_usa:[{id:'A',text:'Find an analogy or story that makes it click — you enjoy this'},{id:'B',text:'Walk through it carefully step by step'},{id:'C',text:'Draw a diagram or create a visual'},{id:'D',text:'Struggle — simplifying your own expertise is genuinely hard'}] },

  // ── IP×6 ───────────────────────────────────────────────────────
  { question_id:'D3-IP-001', dimension:'D3', facet:'Verbal vs Numerical', type:'IP', timer_seconds:8,
    text_india:'Which feels more like you?',
    text_usa:'Which feels more like you?',
    options_india:[{id:'A',text:'Good with words and language'},{id:'B',text:'Good with numbers and data'}],
    options_usa:[{id:'A',text:'Words and language'},{id:'B',text:'Numbers and data'}] },
  { question_id:'D3-IP-002', dimension:'D3', facet:'Verbal vs Spatial', type:'IP', timer_seconds:8,
    text_india:'How do you prefer to understand something?',
    text_usa:'How do you prefer to understand something?',
    options_india:[{id:'A',text:'Read about it'},{id:'B',text:'See it visually or drawn out'}],
    options_usa:[{id:'A',text:'Read it in words'},{id:'B',text:'See it visually'}] },
  { question_id:'D3-IP-003', dimension:'D3', facet:'Idea Generation vs Systematic', type:'IP', timer_seconds:8,
    text_india:'Facing a new challenge:',
    text_usa:'Facing a new challenge:',
    options_india:[{id:'A',text:'Generate many possible approaches'},{id:'B',text:'Build a clear plan and follow it'}],
    options_usa:[{id:'A',text:'Generate many possible approaches'},{id:'B',text:'Build a clear plan and follow it'}] },
  { question_id:'D3-IP-004', dimension:'D3', facet:'Natural Aptitude', type:'IP', timer_seconds:8,
    text_india:'Which do you find easier?',
    text_usa:'Which do you find easier?',
    options_india:[{id:'A',text:'Writing — expressing ideas clearly'},{id:'B',text:'Calculating — working with numbers'}],
    options_usa:[{id:'A',text:'Writing — expressing ideas clearly'},{id:'B',text:'Calculating — working with numbers'}] },
  { question_id:'D3-IP-005', dimension:'D3', facet:'Systematic', type:'IP', timer_seconds:8,
    text_india:'When organising something complex:',
    text_usa:'When organising something complex:',
    options_india:[{id:'A',text:'Build a system — checklist, plan, framework'},{id:'B',text:'Feel your way through — systems slow you down'}],
    options_usa:[{id:'A',text:'Build a system — checklist, plan, framework'},{id:'B',text:'Feel your way through — systems slow you down'}] },
  { question_id:'D3-IP-006', dimension:'D3', facet:'Natural Aptitude', type:'IP', timer_seconds:8,
    text_india:'People come to you for:',
    text_usa:'People come to you for:',
    options_india:[{id:'A',text:'Help with words, writing, or communication'},{id:'B',text:'Help with numbers, analysis, or logic'}],
    options_usa:[{id:'A',text:'Help with words, writing, or communication'},{id:'B',text:'Help with numbers, analysis, or logic'}] },

  // ── CS×5 ───────────────────────────────────────────────────────
  { question_id:'D3-CS-001', dimension:'D3', facet:'Natural Aptitude', type:'CS',
    text_india:'The thing I find easiest that most people seem to find hard is...',
    text_usa:'Something I find naturally easy that others seem to struggle with is...' },
  { question_id:'D3-CS-002', dimension:'D3', facet:'Natural Aptitude', type:'CS',
    text_india:'People most often come to me for help with...',
    text_usa:'People most often come to me for help with...' },
  { question_id:'D3-CS-003', dimension:'D3', facet:'Idea Generation', type:'CS',
    text_india:'The way I solve most problems is...',
    text_usa:'My natural approach to solving most problems is...' },
  { question_id:'D3-CS-004', dimension:'D3', facet:'Natural Aptitude', type:'CS',
    text_india:'The skill I am most quietly proud of — that I do not often talk about — is...',
    text_usa:'The ability I am most quietly confident in is...' },
  { question_id:'D3-CS-005', dimension:'D3', facet:'Systematic', type:'CS',
    text_india:'When I need to organise something complicated, I usually...',
    text_usa:'When I face a complex situation, my instinct is...' },
]

export default D3_QUESTIONS
