import { Question } from './types'

export const D4_QUESTIONS: Question[] = [

  // ── SECURITY vs MEANING ── AG×10 ──────────────────────────────
  { question_id:'D4-AG-001', dimension:'D4', facet:'Security vs Meaning', type:'AG',
    text_india:'I would rather do work that feels meaningful than work that pays very well.',
    text_usa:'I would rather do work that matters to me than work that pays significantly more.' },
  { question_id:'D4-AG-002', dimension:'D4', facet:'Security vs Meaning', type:'AG',
    text_india:'Financial stability matters more to me than doing work I love.',
    text_usa:'Financial stability matters more to me than doing work I find deeply meaningful.' },
  { question_id:'D4-AG-003', dimension:'D4', facet:'Security vs Meaning', type:'AG',
    text_india:'I would accept a significant pay cut to do work I find genuinely meaningful.',
    text_usa:'I would accept a significant pay cut to do work I find genuinely meaningful.' },
  { question_id:'D4-AG-004', dimension:'D4', facet:'Security vs Meaning', type:'AG',
    text_india:'Having a stable income is more important to me than having an exciting career.',
    text_usa:'Having stable income matters more to me than having an exciting career path.' },
  { question_id:'D4-AG-005', dimension:'D4', facet:'Security vs Meaning', type:'AG',
    text_india:'I would rather take a risk on something I believe in than stay in a safe situation I do not.',
    text_usa:'I would rather risk something I believe in than stay somewhere safe but unfulfilling.' },
  { question_id:'D4-AG-006', dimension:'D4', facet:'Security vs Meaning', type:'AG',
    text_india:'I find it hard to work hard at something I do not believe in, no matter how well it pays.',
    text_usa:'I find it difficult to give my best to work I do not believe in, regardless of the pay.' },
  { question_id:'D4-AG-007', dimension:'D4', facet:'Security vs Meaning', type:'AG',
    text_india:'The idea of an uncertain but meaningful path excites me more than a stable but predictable one.',
    text_usa:'An uncertain but meaningful path excites me more than a stable but predictable one.' },
  { question_id:'D4-AG-008', dimension:'D4', facet:'Security vs Meaning', type:'AG',
    text_india:'When I imagine the future, financial security features more prominently than purpose.',
    text_usa:'When I think about my future, financial security feels more important than purpose.' },
  { question_id:'D4-AG-009', dimension:'D4', facet:'Security vs Meaning', type:'AG',
    text_india:'I believe that money is a means to an end, not an end in itself.',
    text_usa:'I genuinely believe money is a means to an end, not the goal itself.' },
  { question_id:'D4-AG-010', dimension:'D4', facet:'Security vs Meaning', type:'AG',
    text_india:'I am willing to live with financial uncertainty if the work genuinely matters to me.',
    text_usa:'I can accept financial uncertainty if the work genuinely matters.' },

  // ── RECOGNITION vs EXCELLENCE ── AG×10 ────────────────────────
  { question_id:'D4-AG-011', dimension:'D4', facet:'Recognition vs Excellence', type:'AG',
    text_india:'I care more about knowing my work was excellent than about others recognising it.',
    text_usa:'I care more about knowing my work was excellent than about others recognising it.' },
  { question_id:'D4-AG-012', dimension:'D4', facet:'Recognition vs Excellence', type:'AG',
    text_india:'Being acknowledged for my contributions is genuinely important to how motivated I feel.',
    text_usa:'Being acknowledged and recognised for my contributions genuinely affects my motivation.' },
  { question_id:'D4-AG-013', dimension:'D4', facet:'Recognition vs Excellence', type:'AG',
    text_india:'I would feel more satisfied by excellent work that no one noticed than average work that got applause.',
    text_usa:'I would rather do excellent work nobody noticed than average work that got lots of praise.' },
  { question_id:'D4-AG-014', dimension:'D4', facet:'Recognition vs Excellence', type:'AG',
    text_india:'I find it genuinely frustrating when my effort goes unrecognised.',
    text_usa:'I find it genuinely frustrating when my effort and contributions are not recognised.' },
  { question_id:'D4-AG-015', dimension:'D4', facet:'Recognition vs Excellence', type:'AG',
    text_india:'I set high standards for myself regardless of whether anyone is watching.',
    text_usa:'I hold myself to high standards regardless of whether anyone else is watching.' },

  // ── INDEPENDENCE vs BELONGING ── AG×5 ─────────────────────────
  { question_id:'D4-AG-016', dimension:'D4', facet:'Independence vs Belonging', type:'AG',
    text_india:'I work best when I have full autonomy — my own decisions, my own approach.',
    text_usa:'I work best when I have full autonomy — my own decisions, my own way of doing things.' },
  { question_id:'D4-AG-017', dimension:'D4', facet:'Independence vs Belonging', type:'AG',
    text_india:'Being part of a close, collaborative team matters deeply to me.',
    text_usa:'Being part of a tight, trusted team matters deeply to me.' },
  { question_id:'D4-AG-018', dimension:'D4', facet:'Independence vs Belonging', type:'AG',
    text_india:'I prefer making decisions on my own rather than by committee.',
    text_usa:'I prefer making decisions independently rather than by consensus.' },
  { question_id:'D4-AG-019', dimension:'D4', facet:'Independence vs Belonging', type:'AG',
    text_india:'The feeling of belonging — being part of something together — is very important to me.',
    text_usa:'The sense of belonging — being truly part of something with others — is very important to me.' },
  { question_id:'D4-AG-020', dimension:'D4', facet:'Independence vs Belonging', type:'AG',
    text_india:'I am more motivated when I own something completely than when responsibility is shared.',
    text_usa:'I am more motivated when I have full ownership than when responsibility is shared.' },

  // ── INSTANT PICKS ── IP×10 ────────────────────────────────────
  { question_id:'D4-IP-001', dimension:'D4', facet:'Security vs Meaning', type:'IP', timer_seconds:8,
    text_india:'Quick — which do you actually want?',
    text_usa:'Quick — which do you actually want?',
    options_india:[{id:'A',text:'Work you love — lower pay, less stable'},{id:'B',text:'Work that is fine — higher pay, stable'}],
    options_usa:[{id:'A',text:'Work you love with lower pay'},{id:'B',text:'Work that is fine with higher pay'}] },
  { question_id:'D4-IP-002', dimension:'D4', facet:'Security vs Meaning', type:'IP', timer_seconds:8,
    text_india:'Your gut says:',
    text_usa:'Your gut says:',
    options_india:[{id:'A',text:'Risky path you believe in'},{id:'B',text:'Safe path you are not sure about'}],
    options_usa:[{id:'A',text:'Risk something you believe in'},{id:'B',text:'Play it safe with something you do not'}] },
  { question_id:'D4-IP-003', dimension:'D4', facet:'Recognition vs Excellence', type:'IP', timer_seconds:8,
    text_india:'Which matters more — honestly?',
    text_usa:'Which matters more — honestly?',
    options_india:[{id:'A',text:'Be recognised publicly for your work'},{id:'B',text:'Know privately that your work was excellent'}],
    options_usa:[{id:'A',text:'Public recognition'},{id:'B',text:'Private knowledge of excellence'}] },
  { question_id:'D4-IP-004', dimension:'D4', facet:'Independence vs Belonging', type:'IP', timer_seconds:8,
    text_india:'At work, which do you actually prefer?',
    text_usa:'At work, which do you actually prefer?',
    options_india:[{id:'A',text:'Work independently'},{id:'B',text:'Work closely with a team'}],
    options_usa:[{id:'A',text:'Work alone'},{id:'B',text:'Work as part of a close team'}] },
  { question_id:'D4-IP-005', dimension:'D4', facet:'Present vs Future', type:'IP', timer_seconds:8,
    text_india:'How you actually live:',
    text_usa:'How you actually live:',
    options_india:[{id:'A',text:'Enjoy life now — spend, experience, be present'},{id:'B',text:'Build for the future — save, invest, delay'}],
    options_usa:[{id:'A',text:'Live fully now'},{id:'B',text:'Build carefully for later'}] },
  { question_id:'D4-IP-006', dimension:'D4', facet:'Individual vs Collective', type:'IP', timer_seconds:8,
    text_india:'Your deeper motivation:',
    text_usa:'Your deeper motivation:',
    options_india:[{id:'A',text:'Career that makes you successful individually'},{id:'B',text:'Career that contributes to something larger'}],
    options_usa:[{id:'A',text:'Your own individual success'},{id:'B',text:'Contribution to something beyond yourself'}] },
  { question_id:'D4-IP-007', dimension:'D4', facet:'Honesty vs Harmony', type:'IP', timer_seconds:8,
    text_india:'In the moment — what do you actually do?',
    text_usa:'In the moment — what do you actually do?',
    options_india:[{id:'A',text:'Say the uncomfortable truth'},{id:'B',text:'Keep the peace and say nothing'}],
    options_usa:[{id:'A',text:'Say the difficult truth'},{id:'B',text:'Preserve the relationship and stay quiet'}] },
  { question_id:'D4-IP-008', dimension:'D4', facet:'Security vs Meaning', type:'IP', timer_seconds:8,
    text_india:'For your life — honestly:',
    text_usa:'For your life — honestly:',
    options_india:[{id:'A',text:'Comfortable, predictable, respected'},{id:'B',text:'Uncertain, exciting, meaningful'}],
    options_usa:[{id:'A',text:'Comfortable and predictable'},{id:'B',text:'Uncertain but meaningful'}] },
  { question_id:'D4-IP-009', dimension:'D4', facet:'Recognition vs Excellence', type:'IP', timer_seconds:8,
    text_india:'Which do you actually want more?',
    text_usa:'Which do you actually want more?',
    options_india:[{id:'A',text:'People think you are brilliant'},{id:'B',text:'You know you did your best work'}],
    options_usa:[{id:'A',text:'Others think you are brilliant'},{id:'B',text:'You know it was your best'}] },
  { question_id:'D4-IP-010', dimension:'D4', facet:'Independence vs Belonging', type:'IP', timer_seconds:8,
    text_india:'Your ideal:',
    text_usa:'Your ideal:',
    options_india:[{id:'A',text:'Complete autonomy — no one to answer to'},{id:'B',text:'Deep belonging — part of something larger'}],
    options_usa:[{id:'A',text:'Complete autonomy'},{id:'B',text:'Deep sense of belonging'}] },

  // ── THIS OR THAT ── TC×10 ──────────────────────────────────────
  { question_id:'D4-TC-001', dimension:'D4', facet:'Security vs Meaning', type:'TC',
    text_india:'Which job would you actually take?',
    text_usa:'Which job would you actually take?',
    options_india:[{id:'A',text:'Top company, work that does not excite you'},{id:'B',text:'Small startup, work you believe in'}],
    options_usa:[{id:'A',text:'Prestigious company, unexciting work'},{id:'B',text:'Small startup, work you believe in'}] },
  { question_id:'D4-TC-002', dimension:'D4', facet:'Security vs Meaning', type:'TC',
    text_india:'Which would you choose?',
    text_usa:'Which would you choose?',
    options_india:[{id:'A',text:'High salary in a stable but dull industry'},{id:'B',text:'Lower salary in an exciting field you love'}],
    options_usa:[{id:'A',text:'High salary, dull industry'},{id:'B',text:'Lower salary, exciting field'}] },
  { question_id:'D4-TC-003', dimension:'D4', facet:'Recognition vs Excellence', type:'TC',
    text_india:'Which would you prefer?',
    text_usa:'Which would you prefer?',
    options_india:[{id:'A',text:'Work that gets public recognition even if not your best'},{id:'B',text:'Work nobody notices that you know is excellent'}],
    options_usa:[{id:'A',text:'Public recognition for average work'},{id:'B',text:'Private satisfaction from excellent work'}] },
  { question_id:'D4-TC-004', dimension:'D4', facet:'Independence vs Belonging', type:'TC',
    text_india:'For your career:',
    text_usa:'For your career:',
    options_india:[{id:'A',text:'Working completely independently'},{id:'B',text:'Being deeply embedded in a strong team'}],
    options_usa:[{id:'A',text:'Complete independence'},{id:'B',text:'Deep team belonging'}] },
  { question_id:'D4-TC-005', dimension:'D4', facet:'Honesty vs Harmony', type:'TC',
    text_india:'A close friend is making a serious mistake. You:',
    text_usa:'A close friend is making a serious mistake. You:',
    options_india:[{id:'A',text:'Tell them honestly — even if it creates conflict'},{id:'B',text:'Be supportive even if you have doubts'}],
    options_usa:[{id:'A',text:'Tell them the uncomfortable truth'},{id:'B',text:'Be supportive and stay quiet'}] },
  { question_id:'D4-TC-006', dimension:'D4', facet:'Present vs Future', type:'TC',
    text_india:'Which matters more right now?',
    text_usa:'Which matters more right now?',
    options_india:[{id:'A',text:'A salary that lets you live very well now'},{id:'B',text:'Equity in something that could be worth a lot later'}],
    options_usa:[{id:'A',text:'Live very well now'},{id:'B',text:'Build toward something potentially large later'}] },
  { question_id:'D4-TC-007', dimension:'D4', facet:'Individual vs Collective', type:'TC',
    text_india:'Which achievement means more?',
    text_usa:'Which achievement means more?',
    options_india:[{id:'A',text:'Achieve something great as an individual'},{id:'B',text:'Be part of a team that achieves something great together'}],
    options_usa:[{id:'A',text:'Individual achievement'},{id:'B',text:'Collective achievement'}] },
  { question_id:'D4-TC-008', dimension:'D4', facet:'Security vs Meaning', type:'TC',
    text_india:'Guaranteed for life — which do you take?',
    text_usa:'Guaranteed for life — which do you take?',
    options_india:[{id:'A',text:'You will always be financially secure'},{id:'B',text:'Your work will genuinely matter'}],
    options_usa:[{id:'A',text:'Financial security guaranteed'},{id:'B',text:'Work that genuinely matters'}] },
  { question_id:'D4-TC-009', dimension:'D4', facet:'Honesty vs Harmony', type:'TC',
    text_india:'Which kind of feedback do you actually give?',
    text_usa:'Which kind of feedback do you actually give?',
    options_india:[{id:'A',text:'Honest feedback that might hurt'},{id:'B',text:'Kind feedback that does not fully help'}],
    options_usa:[{id:'A',text:'Honest feedback that stings'},{id:'B',text:'Kind feedback that avoids the issue'}] },
  { question_id:'D4-TC-010', dimension:'D4', facet:'Individual vs Collective', type:'TC',
    text_india:'What do you want to build?',
    text_usa:'What do you want to build?',
    options_india:[{id:'A',text:'Your own wealth'},{id:'B',text:'Something that outlasts you'}],
    options_usa:[{id:'A',text:'Build personal wealth'},{id:'B',text:'Build something that outlasts you'}] },

  // ── SC×10 ─────────────────────────────────────────────────────
  { question_id:'D4-SC-001', dimension:'D4', facet:'Security vs Meaning', type:'SC',
    text_india:"Your family expects engineering or medicine. You want to be a filmmaker. What do you do?",
    text_usa:"Your background points toward a stable career. Your real interest is in an uncertain field. What do you do?",
    options_india:[{id:'A',text:'Pursue filmmaking — you will regret not trying'},{id:'B',text:'Take the safer path — your family is right'},{id:'C',text:'Try to do both — study and film on the side'},{id:'D',text:'Have not decided — this is genuinely difficult'}],
    options_usa:[{id:'A',text:'Follow the uncertain path — you believe it is right'},{id:'B',text:'Take the stable path — you value security'},{id:'C',text:'Pursue both — maintain security while exploring'},{id:'D',text:'You genuinely have not decided'}] },
  { question_id:'D4-SC-002', dimension:'D4', facet:'Honesty vs Harmony', type:'SC',
    text_india:"Your close friend is about to make a major life decision you think is a serious mistake. You?",
    text_usa:"A close friend is about to make a major decision you believe is a serious mistake. You?",
    options_india:[{id:'A',text:'Tell them honestly — even if it creates conflict'},{id:'B',text:'Share your concern once, then support whatever they choose'},{id:'C',text:'Support them fully — it is their life'},{id:'D',text:'Say nothing — it is not your place'}],
    options_usa:[{id:'A',text:'Tell them honestly and clearly, even if it causes friction'},{id:'B',text:'Share your concern once and then support their choice'},{id:'C',text:'Support them — it is their life and their decision'},{id:'D',text:'Say nothing — it is not your place to interfere'}] },
  { question_id:'D4-SC-003', dimension:'D4', facet:'Recognition vs Excellence', type:'SC',
    text_india:"You did the real work on a group project but a classmate gets most of the credit. You?",
    text_usa:"You did the substantive work but a colleague gets most of the credit in the meeting. You?",
    options_india:[{id:'A',text:'Correct the record — speak up and clarify what you did'},{id:'B',text:'Let it go this time but note it for the future'},{id:'C',text:'Feel genuinely frustrated but say nothing'},{id:'D',text:'It does not bother you — you know what you did'}],
    options_usa:[{id:'A',text:'Speak up and correct the record clearly'},{id:'B',text:'Note it privately and raise it later'},{id:'C',text:'Feel frustrated but say nothing in the moment'},{id:'D',text:'It does not really bother you — you know what you contributed'}] },
  { question_id:'D4-SC-004', dimension:'D4', facet:'Present vs Future', type:'SC',
    text_india:"You receive ₹1 lakh as a gift. What do you do with it?",
    text_usa:"You receive $2,000 unexpectedly. What do you do?",
    options_india:[{id:'A',text:'Invest it — you are building for the future'},{id:'B',text:'Split it — some now, some saved'},{id:'C',text:'Spend most of it — you work hard and deserve it'},{id:'D',text:'Give some away — to family or a cause you believe in'}],
    options_usa:[{id:'A',text:'Invest it — you are building for the long term'},{id:'B',text:'Split it — invest some, enjoy some'},{id:'C',text:'Spend most of it — life is short and you earned it'},{id:'D',text:'Give some away — to someone who needs it more'}] },
  { question_id:'D4-SC-005', dimension:'D4', facet:'Individual vs Collective', type:'SC',
    text_india:"Scholarship to study abroad alone, OR chance to stay and build something important with your team. Which?",
    text_usa:"A prestigious individual fellowship abroad, OR staying to see an important team project through. Which?",
    options_india:[{id:'A',text:'The scholarship — this is your chance'},{id:'B',text:'Stay and build — your team needs you'},{id:'C',text:'Try to find a way to do both'},{id:'D',text:'It genuinely depends on what is being built'}],
    options_usa:[{id:'A',text:'Take it — this is the opportunity you have worked toward'},{id:'B',text:'Stay — your team depends on you right now'},{id:'C',text:'Try to negotiate something that serves both'},{id:'D',text:'It depends on the specifics'}] },
  { question_id:'D4-SC-006', dimension:'D4', facet:'Honesty vs Harmony', type:'SC',
    text_india:"Family discussion about your career — parents push you toward a path you disagree with. You?",
    text_usa:"In a performance review, your manager gives you feedback you strongly disagree with. You?",
    options_india:[{id:'A',text:'State your view clearly and hold your ground'},{id:'B',text:'Share your view once, then find a compromise'},{id:'C',text:'Go along with it for now — the argument is not worth it'},{id:'D',text:'Feel unable to say what you actually think'}],
    options_usa:[{id:'A',text:'Respectfully but clearly disagree and make your case'},{id:'B',text:'Note your disagreement once and then move forward'},{id:'C',text:'Accept the feedback — it is not worth the conflict'},{id:'D',text:'Feel unable to push back in the moment'}] },
  { question_id:'D4-SC-007', dimension:'D4', facet:'Security vs Meaning', type:'SC',
    text_india:"Two offers: ₹15 LPA stable company boring work vs ₹8 LPA startup exciting work. Which?",
    text_usa:"Two offers: $120K Fortune 500 unexciting role vs $75K startup genuinely exciting work. You take?",
    options_india:[{id:'A',text:'The startup — money is not everything'},{id:'B',text:'The large company — ₹15 LPA is significant'},{id:'C',text:'Try to negotiate the startup package first'},{id:'D',text:'Ask for more time — this is hard'}],
    options_usa:[{id:'A',text:'The startup — the work matters more'},{id:'B',text:'The Fortune 500 — $120K is significant'},{id:'C',text:'Try to negotiate the startup offer higher first'},{id:'D',text:'It is a genuinely hard call'}] },
  { question_id:'D4-SC-008', dimension:'D4', facet:'Independence vs Belonging', type:'SC',
    text_india:"Work completely independently — full freedom, no boss. Or be part of a tight talented team. Which?",
    text_usa:"Complete professional independence — no one to report to. Or deep membership in a high-performing team. Which?",
    options_india:[{id:'A',text:'Independence — always'},{id:'B',text:'The team — always'},{id:'C',text:'Independence professionally, belonging personally'},{id:'D',text:'It depends entirely on what is being built'}],
    options_usa:[{id:'A',text:'Independence — always'},{id:'B',text:'The team — always'},{id:'C',text:'Professionally independent, personally connected'},{id:'D',text:'Entirely depends on the opportunity'}] },
  { question_id:'D4-SC-009', dimension:'D4', facet:'Honesty vs Harmony', type:'SC',
    text_india:"You see a classmate being treated unfairly by a teacher in front of others. What do you do?",
    text_usa:"You witness a colleague being publicly treated unfairly by a senior manager. You?",
    options_india:[{id:'A',text:'Speak up — this is not right'},{id:'B',text:'Support your classmate after, not in the moment'},{id:'C',text:'Say nothing — getting involved could make it worse'},{id:'D',text:'You would want to help but probably would not in the moment'}],
    options_usa:[{id:'A',text:'Speak up in the moment — this is not right'},{id:'B',text:'Support them privately afterward'},{id:'C',text:'Say nothing — getting involved could backfire'},{id:'D',text:'You would want to say something but probably would not'}] },
  { question_id:'D4-SC-010', dimension:'D4', facet:'Individual vs Collective', type:'SC',
    text_india:"Build a startup that could make you very wealthy. Or join a government programme helping thousands. Which?",
    text_usa:"Build a startup that could make you very wealthy. Or join a nonprofit directly helping thousands. Which?",
    options_india:[{id:'A',text:'The startup — impact through building'},{id:'B',text:'The government programme — direct social impact'},{id:'C',text:'Social enterprise — find a way to do both'},{id:'D',text:'Neither really captures what I want'}],
    options_usa:[{id:'A',text:'The startup — impact through building something'},{id:'B',text:'The nonprofit — direct and measurable social impact'},{id:'C',text:'Social enterprise — find a way to do both'},{id:'D',text:'Neither captures what I am actually looking for'}] },

  // ── CS×10 ─────────────────────────────────────────────────────
  { question_id:'D4-CS-001', dimension:'D4', facet:'Security vs Meaning', type:'CS',
    text_india:'If I could only have one of these, I would choose meaningful work over financial security because...',
    text_usa:'If forced to choose only one — meaningful work OR financial security — I would choose... because...' },
  { question_id:'D4-CS-002', dimension:'D4', facet:'Recognition vs Excellence', type:'CS',
    text_india:'The type of recognition that means most to me is...',
    text_usa:'The recognition that means most to me — more than any other — is...' },
  { question_id:'D4-CS-003', dimension:'D4', facet:'Independence vs Belonging', type:'CS',
    text_india:'When I do my best work, I am usually...',
    text_usa:'The conditions in which I produce my best work are...' },
  { question_id:'D4-CS-004', dimension:'D4', facet:'Honesty vs Harmony', type:'CS',
    text_india:'When someone I care about is making a mistake, I usually...',
    text_usa:'When someone I care about is clearly making a mistake, I...' },
  { question_id:'D4-CS-005', dimension:'D4', facet:'Individual vs Collective', type:'CS',
    text_india:'The idea of success that feels most true for me is...',
    text_usa:'My personal definition of success — the one that is actually mine — is...' },
  { question_id:'D4-CS-006', dimension:'D4', facet:'Present vs Future', type:'CS',
    text_india:'When it comes to money and the future, the way I actually behave — not the way I think I should — is...',
    text_usa:'My honest relationship with money and the future is...' },
  { question_id:'D4-CS-007', dimension:'D4', facet:'Security vs Meaning', type:'CS',
    text_india:'The career I would choose if I knew I could not fail is...',
    text_usa:'If failure were not possible, the career I would pursue is...' },
  { question_id:'D4-CS-008', dimension:'D4', facet:'Values', type:'CS',
    text_india:'The thing I value most that I feel I rarely get to prioritise is...',
    text_usa:'The value I hold most deeply that my current life does not fully reflect is...' },
  { question_id:'D4-CS-009', dimension:'D4', facet:'Honesty vs Harmony', type:'CS',
    text_india:'The thing I often want to say but do not is...',
    text_usa:'The thing I want to say to the people around me but hold back is...' },
  { question_id:'D4-CS-010', dimension:'D4', facet:'Individual vs Collective', type:'CS',
    text_india:'In ten years, the thing I most want to be able to say I did is...',
    text_usa:'In ten years, what I most want to be able to say about my life is...' },
]

export default D4_QUESTIONS
