import { Question } from './types'

export const D5_QUESTIONS: Question[] = [
  // ── STRESS RESPONSE ── AG×15 ──────────────────────────────────
  { question_id:'D5-AG-001', dimension:'D5', facet:'Stress Response', type:'AG',
    text_india:'Under real pressure, I tend to confront problems directly rather than avoid them.',
    text_usa:'Under real pressure, I confront problems head-on rather than stepping back.' },
  { question_id:'D5-AG-002', dimension:'D5', facet:'Stress Response', type:'AG',
    text_india:'When things get overwhelming, I tend to withdraw and go quiet.',
    text_usa:'When things get overwhelming, my instinct is to withdraw and get quiet.' },
  { question_id:'D5-AG-003', dimension:'D5', facet:'Stress Response', type:'AG',
    text_india:'When I am stressed, I sometimes freeze — I cannot seem to move forward.',
    text_usa:'Under high stress, I sometimes freeze up completely and cannot make progress.' },
  { question_id:'D5-AG-004', dimension:'D5', facet:'Stress Response', type:'AG',
    text_india:'When conflict arises, my first instinct is to make sure everyone is okay.',
    text_usa:'In conflict, my first instinct is to smooth things over and make everyone comfortable.' },
  { question_id:'D5-AG-005', dimension:'D5', facet:'Stress Response', type:'AG',
    text_india:'I perform better under pressure than in low-stakes situations.',
    text_usa:'I actually perform better when the stakes are high than when they are low.' },
  { question_id:'D5-AG-006', dimension:'D5', facet:'Stress Response', type:'AG',
    text_india:'I find it difficult to make decisions when I am under a lot of pressure.',
    text_usa:'Making decisions becomes genuinely difficult when I am under significant pressure.' },
  { question_id:'D5-AG-007', dimension:'D5', facet:'Pressure Performance', type:'AG',
    text_india:'I stay calm and clear-headed in crisis situations.',
    text_usa:'In a crisis, I stay calm and can think clearly under pressure.' },
  { question_id:'D5-AG-008', dimension:'D5', facet:'Pressure Performance', type:'AG',
    text_india:'High-pressure deadlines bring out the best in me.',
    text_usa:'Tight deadlines and high pressure tend to bring out my best work.' },
  { question_id:'D5-AG-009', dimension:'D5', facet:'Recovery', type:'AG',
    text_india:'I recover quickly after difficult or stressful experiences.',
    text_usa:'I bounce back relatively quickly after stressful or difficult experiences.' },
  { question_id:'D5-AG-010', dimension:'D5', facet:'Recovery', type:'AG',
    text_india:'I tend to dwell on difficult experiences for longer than I would like.',
    text_usa:'I tend to replay difficult experiences in my mind longer than I would like.' },
  { question_id:'D5-AG-011', dimension:'D5', facet:'Empathy', type:'AG',
    text_india:'I absorb other people\'s stress and anxiety as if it were my own.',
    text_usa:'I absorb other people\'s stress and anxiety easily — it affects me as if it were mine.' },
  { question_id:'D5-AG-012', dimension:'D5', facet:'Empathy', type:'AG',
    text_india:'I can stay emotionally separate from others\' problems, even when they are serious.',
    text_usa:'I can stay emotionally detached from others\' problems even when they are serious.' },
  { question_id:'D5-AG-013', dimension:'D5', facet:'Regulation', type:'AG',
    text_india:'I am good at managing my emotions in professional or public settings.',
    text_usa:'I am good at managing my emotions in professional or public situations.' },
  { question_id:'D5-AG-014', dimension:'D5', facet:'Regulation', type:'AG',
    text_india:'My emotions sometimes get the better of me at the wrong moments.',
    text_usa:'My emotions sometimes get the better of me at inconvenient moments.' },
  { question_id:'D5-AG-015', dimension:'D5', facet:'Resilience', type:'AG',
    text_india:'I would describe myself as emotionally resilient — difficult experiences make me stronger.',
    text_usa:'I consider myself emotionally resilient — hard experiences tend to strengthen me.' },

  // ── IP QUESTIONS ── timer 8s ───────────────────────────────────
  { question_id:'D5-IP-001', dimension:'D5', facet:'Stress Response', type:'IP', timer_seconds:8,
    text_india:'When something goes seriously wrong — your gut move:',
    text_usa:'When something goes seriously wrong — your gut move:',
    options_india:[{id:'A',text:'Attack it — take control, start solving'},{id:'B',text:'Step back — you need space before you can act'}],
    options_usa:[{id:'A',text:'Attack it — take control immediately'},{id:'B',text:'Step back and process before acting'}] },
  { question_id:'D5-IP-002', dimension:'D5', facet:'Stress Response', type:'IP', timer_seconds:8,
    text_india:'Publicly blamed for something that was not entirely your fault:',
    text_usa:'Publicly blamed for something that was not entirely your fault:',
    options_india:[{id:'A',text:'Clarify your part right there'},{id:'B',text:'Stay quiet — address it later'}],
    options_usa:[{id:'A',text:'Clarify your part immediately'},{id:'B',text:'Stay quiet — address it privately later'}] },
  { question_id:'D5-IP-003', dimension:'D5', facet:'Pressure Performance', type:'IP', timer_seconds:8,
    text_india:'High stakes presentation in 10 minutes. You:',
    text_usa:'High stakes presentation in 10 minutes. You:',
    options_india:[{id:'A',text:'Feel sharp — pressure focuses you'},{id:'B',text:'Feel anxious — pressure unsettles you'}],
    options_usa:[{id:'A',text:'Feel sharp — pressure focuses you'},{id:'B',text:'Feel anxious — pressure unsettles you'}] },
  { question_id:'D5-IP-004', dimension:'D5', facet:'Empathy', type:'IP', timer_seconds:8,
    text_india:'Someone near you is visibly upset. You:',
    text_usa:'Someone near you is visibly upset. You:',
    options_india:[{id:'A',text:'Feel it too — their emotion reaches you'},{id:'B',text:'Observe it — you stay emotionally separate'}],
    options_usa:[{id:'A',text:'Feel it too — their emotion reaches you'},{id:'B',text:'Notice it but stay emotionally separate'}] },
  { question_id:'D5-IP-005', dimension:'D5', facet:'Recovery', type:'IP', timer_seconds:8,
    text_india:'After a genuinely difficult day:',
    text_usa:'After a genuinely difficult day:',
    options_india:[{id:'A',text:'You recover quickly — next day is fresh'},{id:'B',text:'It stays with you — takes time to shake off'}],
    options_usa:[{id:'A',text:'You reset quickly — next day is fresh'},{id:'B',text:'It lingers — takes real time to shake off'}] },

  // ── TC QUESTIONS ───────────────────────────────────────────────
  { question_id:'D5-TC-001', dimension:'D5', facet:'Stress Response', type:'TC',
    text_india:'When things get hard:',
    text_usa:'When things get hard:',
    options_india:[{id:'A',text:'Push through — intensity helps you focus'},{id:'B',text:'Pull back — you need to regroup before pushing on'}],
    options_usa:[{id:'A',text:'Push harder — pressure brings focus'},{id:'B',text:'Pull back and regroup before pushing forward'}] },
  { question_id:'D5-TC-002', dimension:'D5', facet:'Empathy', type:'TC',
    text_india:'A friend is going through something painful:',
    text_usa:'A friend is going through something painful:',
    options_india:[{id:'A',text:'You feel it with them — deeply'},{id:'B',text:'You help them through it while staying separate'}],
    options_usa:[{id:'A',text:'You feel it deeply with them'},{id:'B',text:'You help them while staying emotionally separate'}] },
  { question_id:'D5-TC-003', dimension:'D5', facet:'Regulation', type:'TC',
    text_india:'In a heated argument:',
    text_usa:'In a heated argument:',
    options_india:[{id:'A',text:'You stay controlled — emotions do not take over'},{id:'B',text:'Emotions affect how you come across — you feel it strongly'}],
    options_usa:[{id:'A',text:'You stay controlled — emotions do not take over'},{id:'B',text:'Your emotions affect how you come across'}] },
  { question_id:'D5-TC-004', dimension:'D5', facet:'Recovery', type:'TC',
    text_india:'After a failure that mattered:',
    text_usa:'After a failure that mattered:',
    options_india:[{id:'A',text:'You process it and move on within days'},{id:'B',text:'It sits with you for a while before you can fully move on'}],
    options_usa:[{id:'A',text:'You process it and move forward within days'},{id:'B',text:'It takes real time before you can fully move past it'}] },
  { question_id:'D5-TC-005', dimension:'D5', facet:'Pressure Performance', type:'TC',
    text_india:'Your best work happens when:',
    text_usa:'Your best work happens when:',
    options_india:[{id:'A',text:'There is real pressure and the stakes are high'},{id:'B',text:'You have space, time, and low pressure to do it well'}],
    options_usa:[{id:'A',text:'There is real pressure and high stakes'},{id:'B',text:'You have space, time, and no pressure to rush'}] },

  // ── SC QUESTIONS ───────────────────────────────────────────────
  { question_id:'D5-SC-001', dimension:'D5', facet:'Stress Response', type:'SC',
    text_india:"Everything goes wrong at once — exam results are bad, a friendship falls apart, family tension is high. What actually happens inside you?",
    text_usa:"Everything goes wrong at once — a project fails, an important relationship fractures, financial pressure hits. What actually happens inside you?",
    options_india:[{id:'A',text:'You activate — start tackling each problem one by one'},{id:'B',text:'You withdraw — need space before you can engage'},{id:'C',text:'You freeze — cannot seem to move on any of it'},{id:'D',text:'You focus on keeping others okay before yourself'}],
    options_usa:[{id:'A',text:'You activate — start tackling problems systematically'},{id:'B',text:'You withdraw — need space before you can engage'},{id:'C',text:'You freeze — cannot seem to move forward on any of it'},{id:'D',text:'You focus on managing others\'s reactions before your own'}] },
  { question_id:'D5-SC-002', dimension:'D5', facet:'Pressure Performance', type:'SC',
    text_india:"You have 48 hours to complete something important that would normally take two weeks. What happens?",
    text_usa:"You have 48 hours to deliver something that would normally take two weeks. What happens?",
    options_india:[{id:'A',text:'You rise to it — constraints sharpen your thinking'},{id:'B',text:'You manage it — stressful but you get there'},{id:'C',text:'The quality suffers — pressure hurts your output'},{id:'D',text:'You struggle to start — pressure causes paralysis'}],
    options_usa:[{id:'A',text:'You rise to it — constraints sharpen your thinking'},{id:'B',text:'You manage — it\'s stressful but you deliver'},{id:'C',text:'The quality suffers — pressure hurts your work'},{id:'D',text:'You struggle to start — the pressure causes paralysis'}] },
  { question_id:'D5-SC-003', dimension:'D5', facet:'Recovery', type:'SC',
    text_india:"You fail publicly — a presentation goes badly wrong in front of people who matter. What happens in the next 24 hours?",
    text_usa:"You fail publicly — a presentation or pitch goes badly wrong in front of people who matter. The next 24 hours:",
    options_india:[{id:'A',text:'You process it, extract the lesson, and move on quickly'},{id:'B',text:'It stings — you replay it — but you recover within a few days'},{id:'C',text:'It affects you for a week or more — hard to shake'},{id:'D',text:'You find it genuinely destabilising — it affects your confidence for a while'}],
    options_usa:[{id:'A',text:'You process it, take the lesson, and move on within a day'},{id:'B',text:'It stings — you replay it — but you recover within days'},{id:'C',text:'It affects you for a week or more before you shake it'},{id:'D',text:'It genuinely destabilises you — affects your confidence for a while'}] },
  { question_id:'D5-SC-004', dimension:'D5', facet:'Empathy', type:'SC',
    text_india:"A colleague or friend comes to you in genuine distress. What happens inside you?",
    text_usa:"A colleague or close friend comes to you in genuine distress. What happens inside you?",
    options_india:[{id:'A',text:'You absorb their emotion — it affects you as if it were your own'},{id:'B',text:'You feel genuine concern and want to help — but stay emotionally grounded'},{id:'C',text:'You listen and support — but stay fairly separate emotionally'},{id:'D',text:'You find it uncomfortable — you are not sure what to do with strong emotion from others'}],
    options_usa:[{id:'A',text:'You absorb their emotion — it affects you as if it were your own'},{id:'B',text:'You feel genuine concern and want to help — but stay emotionally grounded'},{id:'C',text:'You listen and support — but stay fairly emotionally separate'},{id:'D',text:'You find strong emotion from others uncomfortable and difficult to respond to'}] },
  { question_id:'D5-SC-005', dimension:'D5', facet:'Regulation', type:'SC',
    text_india:"In an important meeting, someone says something that genuinely angers you. What actually happens?",
    text_usa:"In an important meeting, someone says something that genuinely angers you. What actually happens?",
    options_india:[{id:'A',text:'You address it directly in the moment — controlled but clear'},{id:'B',text:'You feel it strongly but say nothing in the meeting — raise it afterward'},{id:'C',text:'It shows on your face even if you say nothing'},{id:'D',text:'You go quiet and people can tell something is wrong'}],
    options_usa:[{id:'A',text:'You address it directly in the moment — calmly but clearly'},{id:'B',text:'You feel it but say nothing in the meeting — address it afterward'},{id:'C',text:'It shows on your face even if you do not say anything'},{id:'D',text:'You go quiet — people around you can tell something is wrong'}] },

  // ── CS QUESTIONS ───────────────────────────────────────────────
  { question_id:'D5-CS-001', dimension:'D5', facet:'Stress Response', type:'CS',
    text_india:'When I am under real pressure — not ordinary stress, but real pressure — the thing most people do not see is...',
    text_usa:'When I am under real pressure — not ordinary stress, but genuine pressure — the thing most people around me do not see is...' },
  { question_id:'D5-CS-002', dimension:'D5', facet:'Recovery', type:'CS',
    text_india:'After something genuinely difficult, what helps me recover is...',
    text_usa:'After a genuinely difficult experience, what helps me recover is...' },
  { question_id:'D5-CS-003', dimension:'D5', facet:'Empathy', type:'CS',
    text_india:'When someone I care about is struggling, what happens inside me is...',
    text_usa:'When someone I care about is struggling, what actually happens inside me is...' },
  { question_id:'D5-CS-004', dimension:'D5', facet:'Resilience', type:'CS',
    text_india:'The thing that genuinely scares me — that I do not often admit — is...',
    text_usa:'The thing that genuinely scares me — that I rarely admit — is...' },
  { question_id:'D5-CS-005', dimension:'D5', facet:'Regulation', type:'CS',
    text_india:'The emotion I find hardest to manage in professional situations is...',
    text_usa:'The emotion I find most difficult to manage in professional situations is...' },
]

export default D5_QUESTIONS
