import { Question } from './types'

export const D6_QUESTIONS: Question[] = [
  // ── AG×15 ──────────────────────────────────────────────────────
  { question_id:'D6-AG-001', dimension:'D6', facet:'Achievement Drive', type:'AG',
    text_india:'I set high personal standards and feel genuinely dissatisfied when I fall short of them.',
    text_usa:'I hold myself to high standards and feel genuinely dissatisfied when I fall short.' },
  { question_id:'D6-AG-002', dimension:'D6', facet:'Purpose Orientation', type:'AG',
    text_india:'I need to believe that my work matters — beyond just completing a task — to stay truly engaged.',
    text_usa:'I need to believe my work matters beyond just completing tasks to stay truly motivated.' },
  { question_id:'D6-AG-003', dimension:'D6', facet:'Recognition Drive', type:'AG',
    text_india:'Being acknowledged for my contributions is genuinely important to how motivated I feel.',
    text_usa:'Being acknowledged and recognised for my contributions genuinely affects my motivation.' },
  { question_id:'D6-AG-004', dimension:'D6', facet:'Persistence', type:'AG',
    text_india:'Once I commit to something, I follow through even when it gets difficult and boring.',
    text_usa:'Once I commit to something, I follow through even when it becomes difficult or tedious.' },
  { question_id:'D6-AG-005', dimension:'D6', facet:'Intrinsic Motivation', type:'AG',
    text_india:'I am motivated primarily by the quality of my own work, not by external rewards.',
    text_usa:'I am primarily motivated by the quality of my own work, not by external validation or rewards.' },
  { question_id:'D6-AG-006', dimension:'D6', facet:'Sustaining Energy', type:'AG',
    text_india:'I often lose motivation in the middle of long projects, even ones I cared about at the start.',
    text_usa:'I often lose motivation partway through long projects, even ones I started with enthusiasm.' },
  { question_id:'D6-AG-007', dimension:'D6', facet:'Achievement Drive', type:'AG',
    text_india:'I genuinely enjoy competition — it brings out my best.',
    text_usa:'I genuinely enjoy competition and find it brings out my best performance.' },
  { question_id:'D6-AG-008', dimension:'D6', facet:'Purpose Orientation', type:'AG',
    text_india:'Work that does not feel meaningful to me is genuinely hard to sustain, regardless of the pay.',
    text_usa:'Work that feels meaningless is genuinely hard to sustain for me, regardless of what it pays.' },
  { question_id:'D6-AG-009', dimension:'D6', facet:'Intrinsic Motivation', type:'AG',
    text_india:'I would keep working on something I love even if no one ever recognised it.',
    text_usa:'I would keep working on something I love even if it received no external recognition.' },
  { question_id:'D6-AG-010', dimension:'D6', facet:'Recognition Drive', type:'AG',
    text_india:'Public recognition — being seen to succeed — matters more to me than I usually admit.',
    text_usa:'Public recognition — being visibly successful — matters more to me than I usually admit.' },
  { question_id:'D6-AG-011', dimension:'D6', facet:'Persistence', type:'AG',
    text_india:'I am willing to push through difficulty and discomfort to achieve something I care about.',
    text_usa:'I am willing to push through significant difficulty and discomfort to achieve something I care about.' },
  { question_id:'D6-AG-012', dimension:'D6', facet:'Sustaining Energy', type:'AG',
    text_india:'I find it easy to stay motivated when I have a clear vision of what I am working toward.',
    text_usa:'I find it easy to stay motivated when I have a clear and meaningful goal to work toward.' },
  { question_id:'D6-AG-013', dimension:'D6', facet:'Achievement Drive', type:'AG',
    text_india:'I find it genuinely satisfying to master something difficult.',
    text_usa:'Mastering something genuinely difficult gives me real satisfaction.' },
  { question_id:'D6-AG-014', dimension:'D6', facet:'Purpose Orientation', type:'AG',
    text_india:'I am drawn to work that contributes to something larger than myself.',
    text_usa:'I am drawn to work that contributes to something larger than myself or my organisation.' },
  { question_id:'D6-AG-015', dimension:'D6', facet:'Intrinsic Motivation', type:'AG',
    text_india:'The opinion of others about my work matters less to me than my own evaluation of it.',
    text_usa:'My own evaluation of my work matters more to me than what others think of it.' },

  // ── IP×8 ───────────────────────────────────────────────────────
  { question_id:'D6-IP-001', dimension:'D6', facet:'Achievement vs Recognition', type:'IP', timer_seconds:8,
    text_india:'Which matters more — honestly?',
    text_usa:'Which matters more — be honest:',
    options_india:[{id:'A',text:'Being excellent'},{id:'B',text:'Being recognised as excellent'}],
    options_usa:[{id:'A',text:'Being excellent at what you do'},{id:'B',text:'Being recognised as excellent'}] },
  { question_id:'D6-IP-002', dimension:'D6', facet:'Purpose vs Security', type:'IP', timer_seconds:8,
    text_india:'Which sustains you through hard work?',
    text_usa:'Which sustains you through hard work?',
    options_india:[{id:'A',text:'Believing the work genuinely matters'},{id:'B',text:'Knowing it leads to security and reward'}],
    options_usa:[{id:'A',text:'Believing the work genuinely matters'},{id:'B',text:'Knowing it leads to financial security and reward'}] },
  { question_id:'D6-IP-003', dimension:'D6', facet:'Intrinsic vs Extrinsic', type:'IP', timer_seconds:8,
    text_india:'What keeps you going when a project gets hard?',
    text_usa:'What keeps you going when a project gets genuinely hard?',
    options_india:[{id:'A',text:'Your own standards — you cannot leave it less than your best'},{id:'B',text:'The outcome — what you will achieve or receive when it is done'}],
    options_usa:[{id:'A',text:'Your own standards — you cannot leave it below your best'},{id:'B',text:'The outcome — what you will achieve or get when it is done'}] },
  { question_id:'D6-IP-004', dimension:'D6', facet:'Competition', type:'IP', timer_seconds:8,
    text_india:'Does competition energise or pressure you?',
    text_usa:'Does competition energise or pressurise you?',
    options_india:[{id:'A',text:'Energise — it sharpens me'},{id:'B',text:'Pressure — it makes me more anxious than driven'}],
    options_usa:[{id:'A',text:'Energise — it sharpens my focus'},{id:'B',text:'Pressurise — it makes me anxious rather than driven'}] },
  { question_id:'D6-IP-005', dimension:'D6', facet:'Meaning vs Mastery', type:'IP', timer_seconds:8,
    text_india:'Which motivates you more?',
    text_usa:'Which motivates you more?',
    options_india:[{id:'A',text:'Work that matters — even if hard to master'},{id:'B',text:'Work you can master — even if purpose is unclear'}],
    options_usa:[{id:'A',text:'Work that matters deeply — even if hard to master'},{id:'B',text:'Work you can truly master — even if the purpose is less clear'}] },

  // ── TC×6 ───────────────────────────────────────────────────────
  { question_id:'D6-TC-001', dimension:'D6', facet:'Intrinsic vs Extrinsic', type:'TC',
    text_india:'Which describes why you actually work hard?',
    text_usa:'Which describes why you actually work hard?',
    options_india:[{id:'A',text:'Your own standards — you cannot tolerate doing something badly'},{id:'B',text:'The result — what it leads to, what it gets you'}],
    options_usa:[{id:'A',text:'Your own standards — you cannot tolerate doing something poorly'},{id:'B',text:'The result — what it leads to or earns you'}] },
  { question_id:'D6-TC-002', dimension:'D6', facet:'Purpose Orientation', type:'TC',
    text_india:'Which would keep you going longer?',
    text_usa:'Which would sustain you longer?',
    options_india:[{id:'A',text:'Work that matters deeply — even if it pays less'},{id:'B',text:'Work that pays well — even if it feels meaningless'}],
    options_usa:[{id:'A',text:'Deeply meaningful work — even at lower pay'},{id:'B',text:'Well-paid work — even if it feels meaningless'}] },
  { question_id:'D6-TC-003', dimension:'D6', facet:'Achievement Drive', type:'TC',
    text_india:'Which feels more satisfying?',
    text_usa:'Which feels more satisfying?',
    options_india:[{id:'A',text:'Achieving something very difficult that few can do'},{id:'B',text:'Completing many things well and consistently'}],
    options_usa:[{id:'A',text:'Achieving something very difficult that very few can do'},{id:'B',text:'Completing many things consistently and well'}] },
  { question_id:'D6-TC-004', dimension:'D6', facet:'Persistence', type:'TC',
    text_india:'When you lose motivation mid-project:',
    text_usa:'When you lose motivation in the middle of a project:',
    options_india:[{id:'A',text:'You push through — starting something and not finishing is not acceptable'},{id:'B',text:'You need a reset — you might step back before continuing'}],
    options_usa:[{id:'A',text:'You push through — starting and not finishing is unacceptable to you'},{id:'B',text:'You need a reset — you step back before you can continue'}] },
  { question_id:'D6-TC-005', dimension:'D6', facet:'Recognition Drive', type:'TC',
    text_india:'Which frustrates you more?',
    text_usa:'Which frustrates you more?',
    options_india:[{id:'A',text:'Doing excellent work nobody notices'},{id:'B',text:'Receiving recognition for work you know was not your best'}],
    options_usa:[{id:'A',text:'Doing excellent work that nobody notices or acknowledges'},{id:'B',text:'Receiving recognition for work you know was not your best'}] },
  { question_id:'D6-TC-006', dimension:'D6', facet:'Sustaining Energy', type:'TC',
    text_india:'What energises you most in your work?',
    text_usa:'What energises you most in your work?',
    options_india:[{id:'A',text:'Getting better at something — the feeling of growing'},{id:'B',text:'Making an impact — seeing your work change something'}],
    options_usa:[{id:'A',text:'Getting better — the feeling of real mastery and growth'},{id:'B',text:'Making impact — seeing your work actually change something'}] },

  // ── SC×6 ───────────────────────────────────────────────────────
  { question_id:'D6-SC-001', dimension:'D6', facet:'Intrinsic Motivation', type:'SC',
    text_india:"You spend three months on a project you are proud of. Nobody ever acknowledges it. What happens inside you?",
    text_usa:"You spend three months on a project that you know is your best work. Nobody on the team or above ever acknowledges it. What happens inside you?",
    options_india:[{id:'A',text:'Fine — you know the quality. That is enough.'},{id:'B',text:'Frustrated — effort and quality deserve to be seen.'},{id:'C',text:'Mixed — proud of the work but genuinely bothered by the silence.'},{id:'D',text:'Demotivated — you start questioning whether effort is worth it.'}],
    options_usa:[{id:'A',text:'Fine — you know the quality of your work. That is enough.'},{id:'B',text:'Frustrated — effort and quality should be recognised.'},{id:'C',text:'Mixed — proud of the work but genuinely bothered by the lack of acknowledgment.'},{id:'D',text:'Demotivated — it makes you question whether the effort is worth it.'}] },
  { question_id:'D6-SC-002', dimension:'D6', facet:'Purpose Orientation', type:'SC',
    text_india:"You have been doing good work for a year but you genuinely cannot see who it helps or why it matters. What happens?",
    text_usa:"You have been doing good work for a year but you genuinely cannot see who it helps or why it matters. What happens?",
    options_india:[{id:'A',text:'You disengage — meaning is not optional for you'},{id:'B',text:'You manage — not everything has to feel meaningful'},{id:'C',text:'You look for meaning in the relationships rather than the work itself'},{id:'D',text:'You redouble effort — maybe mastery fills the meaning gap'}],
    options_usa:[{id:'A',text:'You disengage — meaning is not optional for you'},{id:'B',text:'You manage — not everything needs to feel meaningful'},{id:'C',text:'You find meaning in the relationships and people, not the work itself'},{id:'D',text:'You push harder — mastery fills the meaning gap for you'}] },
  { question_id:'D6-SC-003', dimension:'D6', facet:'Persistence', type:'SC',
    text_india:"Halfway through a difficult project, you have lost interest and motivation. What do you actually do?",
    text_usa:"Halfway through a challenging project, you have lost both interest and motivation. What do you actually do?",
    options_india:[{id:'A',text:'Push through — you committed and that is that'},{id:'B',text:'Find a new angle or approach that re-engages you'},{id:'C',text:'Take a break and come back to it'},{id:'D',text:'Genuinely struggle to complete it at the level you wanted'}],
    options_usa:[{id:'A',text:'Push through regardless — you committed and that is that'},{id:'B',text:'Find a new angle or framing that re-engages your interest'},{id:'C',text:'Step back, take a break, and return to it'},{id:'D',text:'Genuinely struggle to finish it at the level you wanted'}] },

  // ── CS×6 ───────────────────────────────────────────────────────
  { question_id:'D6-CS-001', dimension:'D6', facet:'Intrinsic Motivation', type:'CS',
    text_india:'The real reason I work as hard as I do — not the answer that sounds good — is...',
    text_usa:'The real reason I work as hard as I do — not the version I tell people — is...' },
  { question_id:'D6-CS-002', dimension:'D6', facet:'Purpose Orientation', type:'CS',
    text_india:'Work feels genuinely worth doing when...',
    text_usa:'Work feels genuinely worth doing to me when...' },
  { question_id:'D6-CS-003', dimension:'D6', facet:'Sustaining Energy', type:'CS',
    text_india:'The thing that makes me lose motivation fastest is...',
    text_usa:'The thing that drains my motivation faster than anything else is...' },
  { question_id:'D6-CS-004', dimension:'D6', facet:'Achievement Drive', type:'CS',
    text_india:'The achievement I am most proud of — that I rarely talk about — is...',
    text_usa:'The achievement I am most proud of — that I rarely mention — is...' },
  { question_id:'D6-CS-005', dimension:'D6', facet:'Persistence', type:'CS',
    text_india:'When I want to give up on something important, what keeps me going is...',
    text_usa:'When I am closest to giving up on something that matters, what keeps me going is...' },
  { question_id:'D6-CS-006', dimension:'D6', facet:'Recognition Drive', type:'CS',
    text_india:'The kind of recognition that means the most to me is...',
    text_usa:'The type of recognition that genuinely means the most to me is...' },
]

export default D6_QUESTIONS
