import { Question } from './types'

export const D7_QUESTIONS: Question[] = [
  // ── AG×15 ──────────────────────────────────────────────────────
  { question_id:'D7-AG-001', dimension:'D7', facet:'Analytical vs Intuitive', type:'AG',
    text_india:'I trust data and evidence over gut feeling when making decisions.',
    text_usa:'I trust data and evidence more than gut feeling when making important decisions.' },
  { question_id:'D7-AG-002', dimension:'D7', facet:'Analytical vs Intuitive', type:'AG',
    text_india:'I often make good decisions based on instinct before I can fully explain why.',
    text_usa:'I often make good decisions by instinct before I can fully articulate the reasoning.' },
  { question_id:'D7-AG-003', dimension:'D7', facet:'Convergent vs Divergent', type:'AG',
    text_india:'I generate more ideas than I can ever act on — my mind goes wide before it goes deep.',
    text_usa:'I generate far more ideas than I can act on — my mind ranges wide before settling.' },
  { question_id:'D7-AG-004', dimension:'D7', facet:'Detail vs Big Picture', type:'AG',
    text_india:'I naturally focus on the detail and precision of things — I notice what others miss.',
    text_usa:'I naturally focus on details and precision — I often notice things others miss.' },
  { question_id:'D7-AG-005', dimension:'D7', facet:'Detail vs Big Picture', type:'AG',
    text_india:'I am more interested in the big picture than in the mechanics of how things work.',
    text_usa:'I am more drawn to the big picture than to the mechanics of how things work.' },
  { question_id:'D7-AG-006', dimension:'D7', facet:'Sequential vs Non-linear', type:'AG',
    text_india:'I prefer to work through problems systematically — one step at a time.',
    text_usa:'I prefer to work through problems step by step in a systematic, ordered way.' },
  { question_id:'D7-AG-007', dimension:'D7', facet:'Sequential vs Non-linear', type:'AG',
    text_india:'My best thinking is non-linear — I jump between ideas and connections emerge unexpectedly.',
    text_usa:'My best thinking is non-linear — I jump around between ideas and connections emerge unexpectedly.' },
  { question_id:'D7-AG-008', dimension:'D7', facet:'Ambiguity Tolerance', type:'AG',
    text_india:'I am comfortable starting something before I fully understand it.',
    text_usa:'I am comfortable diving into something before I fully understand it.' },
  { question_id:'D7-AG-009', dimension:'D7', facet:'Ambiguity Tolerance', type:'AG',
    text_india:'Ambiguity frustrates me — I work better with clear parameters.',
    text_usa:'Ambiguity frustrates me — I work better when the parameters are clear.' },
  { question_id:'D7-AG-010', dimension:'D7', facet:'Depth vs Speed', type:'AG',
    text_india:'I prefer to think slowly and deeply rather than quickly and broadly.',
    text_usa:'I prefer to think slowly and deeply rather than quickly across many things.' },
  { question_id:'D7-AG-011', dimension:'D7', facet:'Convergent vs Divergent', type:'AG',
    text_india:'I find it easy to come up with creative solutions others have not thought of.',
    text_usa:'I find it natural to come up with creative solutions that others have not considered.' },
  { question_id:'D7-AG-012', dimension:'D7', facet:'Analytical vs Intuitive', type:'AG',
    text_india:'I often see patterns and connections that others miss.',
    text_usa:'I frequently see patterns and connections that others around me do not notice.' },
  { question_id:'D7-AG-013', dimension:'D7', facet:'Reflective vs Reactive', type:'AG',
    text_india:'I need time to think before I can give my best response or idea.',
    text_usa:'I need time to think before I can produce my best thinking or response.' },
  { question_id:'D7-AG-014', dimension:'D7', facet:'Reflective vs Reactive', type:'AG',
    text_india:'I think best when talking through problems with others.',
    text_usa:'I think best when I can talk through problems with another person.' },
  { question_id:'D7-AG-015', dimension:'D7', facet:'Depth vs Speed', type:'AG',
    text_india:'I would rather understand one thing deeply than know many things at a surface level.',
    text_usa:'I would always rather understand one thing deeply than know many things superficially.' },

  // ── IP×6 ───────────────────────────────────────────────────────
  { question_id:'D7-IP-001', dimension:'D7', facet:'Analytical vs Intuitive', type:'IP', timer_seconds:8,
    text_india:'How do you actually make decisions?',
    text_usa:'How do you actually make most decisions?',
    options_india:[{id:'A',text:'Research and reason your way to the answer'},{id:'B',text:'Feel your way — trust your instinct'}],
    options_usa:[{id:'A',text:'Research and reason your way to the right answer'},{id:'B',text:'Feel your way — trust the instinct'}] },
  { question_id:'D7-IP-002', dimension:'D7', facet:'Detail vs Big Picture', type:'IP', timer_seconds:8,
    text_india:'Where does your mind naturally go?',
    text_usa:'Where does your mind naturally go?',
    options_india:[{id:'A',text:'The detail — what specifically, how exactly'},{id:'B',text:'The big picture — what it means, where it leads'}],
    options_usa:[{id:'A',text:'The detail — what exactly, how precisely'},{id:'B',text:'The big picture — what it means, where it goes'}] },
  { question_id:'D7-IP-003', dimension:'D7', facet:'Ambiguity Tolerance', type:'IP', timer_seconds:8,
    text_india:'New problem with no clear answer. You:',
    text_usa:'New problem with no clear answer. You:',
    options_india:[{id:'A',text:'Energised — this is interesting'},{id:'B',text:'Unsettled — you need more structure'}],
    options_usa:[{id:'A',text:'Energised — ambiguous problems interest you'},{id:'B',text:'Unsettled — you need more structure to work well'}] },
  { question_id:'D7-IP-004', dimension:'D7', facet:'Reflective vs Reactive', type:'IP', timer_seconds:8,
    text_india:'Think better:',
    text_usa:'You think better:',
    options_india:[{id:'A',text:'Alone — in quiet, solo reflection'},{id:'B',text:'In conversation — ideas emerge by talking'}],
    options_usa:[{id:'A',text:'Alone — in quiet, uninterrupted reflection'},{id:'B',text:'In conversation — ideas emerge when talking'}] },
  { question_id:'D7-IP-005', dimension:'D7', facet:'Convergent vs Divergent', type:'IP', timer_seconds:8,
    text_india:'When solving a problem you prefer to:',
    text_usa:'When solving a problem, you prefer to:',
    options_india:[{id:'A',text:'Generate many possible approaches first'},{id:'B',text:'Find the best single approach and go deep'}],
    options_usa:[{id:'A',text:'Generate many possible approaches first'},{id:'B',text:'Identify the best single approach and go deep'}] },
  { question_id:'D7-IP-006', dimension:'D7', facet:'Sequential vs Non-linear', type:'IP', timer_seconds:8,
    text_india:'Your natural approach to complex work:',
    text_usa:'Your natural approach to complex work:',
    options_india:[{id:'A',text:'Step by step — systematic from start to finish'},{id:'B',text:'All over — multiple threads at once'}],
    options_usa:[{id:'A',text:'Step by step — systematic and ordered'},{id:'B',text:'Multiple threads at once — non-linear'}] },

  // ── TC×6 ───────────────────────────────────────────────────────
  { question_id:'D7-TC-001', dimension:'D7', facet:'Analytical vs Intuitive', type:'TC',
    text_india:'Faced with a difficult decision:',
    text_usa:'Faced with a difficult decision:',
    options_india:[{id:'A',text:'Gather information, analyse, then decide'},{id:'B',text:'Trust the gut — then validate if needed'}],
    options_usa:[{id:'A',text:'Gather information, analyse carefully, then decide'},{id:'B',text:'Trust the gut — validate afterward if needed'}] },
  { question_id:'D7-TC-002', dimension:'D7', facet:'Detail vs Big Picture', type:'TC',
    text_india:'Reading a report:',
    text_usa:'Reading a report or document:',
    options_india:[{id:'A',text:'You read every line — detail matters'},{id:'B',text:'You skim for the key points — detail comes later if needed'}],
    options_usa:[{id:'A',text:'You read every line — you need the full picture'},{id:'B',text:'You skim for key points — you come back to detail if needed'}] },
  { question_id:'D7-TC-003', dimension:'D7', facet:'Convergent vs Divergent', type:'TC',
    text_india:'In a creative challenge:',
    text_usa:'In a creative challenge:',
    options_india:[{id:'A',text:'You generate many ideas and then pick the best'},{id:'B',text:'You quickly identify the best direction and go deep on it'}],
    options_usa:[{id:'A',text:'You generate many ideas then select and refine'},{id:'B',text:'You quickly identify the strongest direction and develop it'}] },
  { question_id:'D7-TC-004', dimension:'D7', facet:'Ambiguity Tolerance', type:'TC',
    text_india:'Open brief — no clear format or rules:',
    text_usa:'Open brief — no clear format or constraints:',
    options_india:[{id:'A',text:'Exciting — freedom lets you do your best work'},{id:'B',text:'Challenging — you work better with some structure'}],
    options_usa:[{id:'A',text:'Exciting — freedom is where you do your best work'},{id:'B',text:'Challenging — some structure helps you work better'}] },
  { question_id:'D7-TC-005', dimension:'D7', facet:'Depth vs Speed', type:'TC',
    text_india:'Which is more like you?',
    text_usa:'Which is more like you?',
    options_india:[{id:'A',text:'Go deep on fewer things — master them'},{id:'B',text:'Cover more ground — know broadly across many areas'}],
    options_usa:[{id:'A',text:'Go deep on fewer things and truly master them'},{id:'B',text:'Cover more ground — know broadly across many areas'}] },
  { question_id:'D7-TC-006', dimension:'D7', facet:'Reflective vs Reactive', type:'TC',
    text_india:'Your best ideas come:',
    text_usa:'Your best ideas tend to come:',
    options_india:[{id:'A',text:'Through deliberate focused effort'},{id:'B',text:'Unexpectedly — in the shower, on a walk, mid-conversation'}],
    options_usa:[{id:'A',text:'Through deliberate, focused thinking effort'},{id:'B',text:'Unexpectedly — in the shower, walking, or mid-conversation'}] },

  // ── SC×4 ───────────────────────────────────────────────────────
  { question_id:'D7-SC-001', dimension:'D7', facet:'Problem Solving', type:'SC',
    text_india:"You are given a problem you have never seen before. No instructions. Walk me through what you actually do first.",
    text_usa:"You are given a genuinely novel problem — no instructions, no precedent. Walk me through what you actually do first.",
    options_india:[{id:'A',text:'Research: find out how others have solved similar problems'},{id:'B',text:'Break it down: define the parts before tackling the whole'},{id:'C',text:'Experiment: try something and learn from what happens'},{id:'D',text:'Think: sit with it quietly before doing anything'}],
    options_usa:[{id:'A',text:'Research: find how others have approached similar problems'},{id:'B',text:'Deconstruct: define the components before tackling the whole'},{id:'C',text:'Experiment: try something and iterate from what you learn'},{id:'D',text:'Think: sit with it quietly before taking any action'}] },
  { question_id:'D7-SC-002', dimension:'D7', facet:'Analytical vs Intuitive', type:'SC',
    text_india:"You have a big decision to make. You have enough information to make a good decision but not perfect information. What do you do?",
    text_usa:"You have an important decision to make. You have enough information to make a good decision but not complete information. What do you do?",
    options_india:[{id:'A',text:'Decide now with what you have — waiting costs more than imperfect information'},{id:'B',text:'Gather more before committing — the risk of being wrong is too high'},{id:'C',text:'Go with your gut — the data confirms what you already sensed'},{id:'D',text:'Consult someone else — a second perspective helps you decide'}],
    options_usa:[{id:'A',text:'Decide now — waiting costs more than imperfect information'},{id:'B',text:'Gather more — the risk of being wrong outweighs the delay'},{id:'C',text:'Trust your instinct — the data confirms what you already felt'},{id:'D',text:'Consult someone — a second perspective helps you move forward'}] },

  // ── CS×5 ───────────────────────────────────────────────────────
  { question_id:'D7-CS-001', dimension:'D7', facet:'Analytical vs Intuitive', type:'CS',
    text_india:'The way I solve most problems is...',
    text_usa:'My natural approach to solving most problems is...' },
  { question_id:'D7-CS-002', dimension:'D7', facet:'Convergent vs Divergent', type:'CS',
    text_india:'The type of thinking I find most natural and energising is...',
    text_usa:'The type of thinking I find most energising and natural is...' },
  { question_id:'D7-CS-003', dimension:'D7', facet:'Depth vs Speed', type:'CS',
    text_india:'I do my best thinking when...',
    text_usa:'My best thinking happens when...' },
  { question_id:'D7-CS-004', dimension:'D7', facet:'Ambiguity Tolerance', type:'CS',
    text_india:'The type of problem I find genuinely irresistible — I cannot leave it alone — is...',
    text_usa:'The type of problem I find genuinely irresistible — that I cannot leave alone — is...' },
  { question_id:'D7-CS-005', dimension:'D7', facet:'Sequential vs Non-linear', type:'CS',
    text_india:'When I am at my intellectual best, I am usually...',
    text_usa:'When I am at my intellectual best, I am usually...' },
]

export default D7_QUESTIONS
