import { Question } from './types'

export const D8_QUESTIONS: Question[] = [
  // ── AG×15 ──────────────────────────────────────────────────────
  { question_id:'D8-AG-001', dimension:'D8', facet:'Independent vs Collaborative', type:'AG',
    text_india:'I do my best work when I work independently, with full ownership and minimal direction.',
    text_usa:'I do my best work when I work independently with full ownership and minimal direction.' },
  { question_id:'D8-AG-002', dimension:'D8', facet:'Independent vs Collaborative', type:'AG',
    text_india:'Being part of a close, collaborative team brings out my best.',
    text_usa:'Being part of a close, high-performing team brings out my best work.' },
  { question_id:'D8-AG-003', dimension:'D8', facet:'Structured vs Flexible', type:'AG',
    text_india:'I work better with clear processes and defined expectations.',
    text_usa:'I work better when there are clear processes and well-defined expectations.' },
  { question_id:'D8-AG-004', dimension:'D8', facet:'Structured vs Flexible', type:'AG',
    text_india:'I find rigid structures and fixed processes frustrating — I need flexibility.',
    text_usa:'Rigid structures and fixed processes frustrate me — I need flexibility to do good work.' },
  { question_id:'D8-AG-005', dimension:'D8', facet:'Fast vs Deliberate', type:'AG',
    text_india:'I make decisions and take action quickly — speed matters more than perfection.',
    text_usa:'I make decisions and act quickly — speed matters more than perfection.' },
  { question_id:'D8-AG-006', dimension:'D8', facet:'Fast vs Deliberate', type:'AG',
    text_india:'I prefer to think carefully and thoroughly before committing to a course of action.',
    text_usa:'I prefer to think carefully and thoroughly before committing to a direction.' },
  { question_id:'D8-AG-007', dimension:'D8', facet:'Leading vs Executing', type:'AG',
    text_india:'I naturally step into a leadership role when a group needs direction.',
    text_usa:'I naturally step into leadership when a group needs direction or organisation.' },
  { question_id:'D8-AG-008', dimension:'D8', facet:'Leading vs Executing', type:'AG',
    text_india:'I prefer to contribute as an expert rather than lead the team.',
    text_usa:'I prefer to contribute as a specialist or expert rather than lead the group.' },
  { question_id:'D8-AG-009', dimension:'D8', facet:'Creating vs Implementing', type:'AG',
    text_india:'I get more energy from building something new than from improving something existing.',
    text_usa:'I get more energy from creating something new than from improving what already exists.' },
  { question_id:'D8-AG-010', dimension:'D8', facet:'Creating vs Implementing', type:'AG',
    text_india:'I take satisfaction in executing well — doing things with precision and consistency.',
    text_usa:'I take real satisfaction in executing well — precision and consistency over novelty.' },
  { question_id:'D8-AG-011', dimension:'D8', facet:'Variety vs Depth', type:'AG',
    text_india:'I thrive with variety — I like switching between different types of work.',
    text_usa:'I thrive with variety — switching between different types of problems energises me.' },
  { question_id:'D8-AG-012', dimension:'D8', facet:'Variety vs Depth', type:'AG',
    text_india:'I prefer to go deep on one thing for a long time rather than spread across many.',
    text_usa:'I prefer sustained, deep focus on one thing rather than spreading across many areas.' },
  { question_id:'D8-AG-013', dimension:'D8', facet:'Independent vs Collaborative', type:'AG',
    text_india:'I find group decision-making slow and frustrating — I prefer to decide and move.',
    text_usa:'Group decision-making feels slow and frustrating to me — I prefer to decide and move.' },
  { question_id:'D8-AG-014', dimension:'D8', facet:'Structured vs Flexible', type:'AG',
    text_india:'I create my own systems and structures when none exist.',
    text_usa:'When clear systems do not exist, I create my own naturally.' },
  { question_id:'D8-AG-015', dimension:'D8', facet:'Leading vs Executing', type:'AG',
    text_india:'I find managing other people\'s work more energising than doing the work myself.',
    text_usa:'I find managing and coordinating others\' work more energising than individual contribution.' },

  // ── IP×6 ───────────────────────────────────────────────────────
  { question_id:'D8-IP-001', dimension:'D8', facet:'Independent vs Collaborative', type:'IP', timer_seconds:8,
    text_india:'For your best work you need:',
    text_usa:'For your best work you need:',
    options_india:[{id:'A',text:'Autonomy — own it completely'},{id:'B',text:'Team — build it together'}],
    options_usa:[{id:'A',text:'Autonomy — own it completely'},{id:'B',text:'Team — build it together'}] },
  { question_id:'D8-IP-002', dimension:'D8', facet:'Structured vs Flexible', type:'IP', timer_seconds:8,
    text_india:'Work environment:',
    text_usa:'Work environment:',
    options_india:[{id:'A',text:'Clear structure and defined processes'},{id:'B',text:'Flexible — figure it out as you go'}],
    options_usa:[{id:'A',text:'Clear structure and defined processes'},{id:'B',text:'Flexible — adapt and figure it out as you go'}] },
  { question_id:'D8-IP-003', dimension:'D8', facet:'Fast vs Deliberate', type:'IP', timer_seconds:8,
    text_india:'Decision-making:',
    text_usa:'Decision-making:',
    options_india:[{id:'A',text:'Fast — good enough and moving beats perfect and slow'},{id:'B',text:'Deliberate — right beats fast every time'}],
    options_usa:[{id:'A',text:'Fast — good and moving beats perfect and slow'},{id:'B',text:'Deliberate — right beats fast every time'}] },
  { question_id:'D8-IP-004', dimension:'D8', facet:'Leading vs Executing', type:'IP', timer_seconds:8,
    text_india:'In a group without a clear leader you:',
    text_usa:'In a leaderless group you:',
    options_india:[{id:'A',text:'Naturally step in and organise'},{id:'B',text:'Contribute your expertise and let someone else lead'}],
    options_usa:[{id:'A',text:'Naturally step in and take charge'},{id:'B',text:'Contribute your expertise without needing to lead'}] },
  { question_id:'D8-IP-005', dimension:'D8', facet:'Creating vs Implementing', type:'IP', timer_seconds:8,
    text_india:'Which energises you more?',
    text_usa:'Which energises you more?',
    options_india:[{id:'A',text:'Building something that does not exist yet'},{id:'B',text:'Making something existing work really well'}],
    options_usa:[{id:'A',text:'Building something that does not exist yet'},{id:'B',text:'Making something existing work exceptionally well'}] },
  { question_id:'D8-IP-006', dimension:'D8', facet:'Variety vs Depth', type:'IP', timer_seconds:8,
    text_india:'Ideal work:',
    text_usa:'Ideal work:',
    options_india:[{id:'A',text:'Variety — different problems, different contexts'},{id:'B',text:'Depth — one domain, mastered completely'}],
    options_usa:[{id:'A',text:'Variety — different problems, different contexts daily'},{id:'B',text:'Depth — one domain, mastered over time'}] },

  // ── TC×6 ───────────────────────────────────────────────────────
  { question_id:'D8-TC-001', dimension:'D8', facet:'Independent vs Collaborative', type:'TC',
    text_india:'Which feels more natural?',
    text_usa:'Which feels more natural?',
    options_india:[{id:'A',text:'Working alone — full control, your own pace'},{id:'B',text:'Working with a close team — shared ownership'}],
    options_usa:[{id:'A',text:'Working alone — full control, your own pace'},{id:'B',text:'Working with a tight team — shared ownership and accountability'}] },
  { question_id:'D8-TC-002', dimension:'D8', facet:'Structured vs Flexible', type:'TC',
    text_india:'Starting a new project:',
    text_usa:'Starting a new project:',
    options_india:[{id:'A',text:'You want a clear brief — scope, timeline, deliverables defined'},{id:'B',text:'You prefer a loose brief — you like figuring out the shape as you go'}],
    options_usa:[{id:'A',text:'You want a clear brief — scope, timeline, deliverables upfront'},{id:'B',text:'You prefer open briefs — you like defining the shape as you go'}] },
  { question_id:'D8-TC-003', dimension:'D8', facet:'Fast vs Deliberate', type:'TC',
    text_india:'Which failure bothers you more?',
    text_usa:'Which failure bothers you more?',
    options_india:[{id:'A',text:'Moving too slow — missing the moment by over-thinking'},{id:'B',text:'Moving too fast — making an avoidable mistake'}],
    options_usa:[{id:'A',text:'Moving too slowly — missing the moment by overthinking'},{id:'B',text:'Moving too fast — making an avoidable mistake'}] },
  { question_id:'D8-TC-004', dimension:'D8', facet:'Leading vs Executing', type:'TC',
    text_india:'Career-wise, which appeals more?',
    text_usa:'Career-wise, which appeals more?',
    options_india:[{id:'A',text:'Build and lead a team doing something important'},{id:'B',text:'Be the best in your domain — a true expert'}],
    options_usa:[{id:'A',text:'Build and lead a team doing something significant'},{id:'B',text:'Be the best in your domain — a true expert individual contributor'}] },
  { question_id:'D8-TC-005', dimension:'D8', facet:'Creating vs Implementing', type:'TC',
    text_india:'Which phase of a project suits you best?',
    text_usa:'Which project phase suits you best?',
    options_india:[{id:'A',text:'The start — figuring out what to build and why'},{id:'B',text:'The middle — executing well on a clear plan'}],
    options_usa:[{id:'A',text:'The start — defining what to build and why'},{id:'B',text:'The middle — executing well against a clear plan'}] },
  { question_id:'D8-TC-006', dimension:'D8', facet:'Variety vs Depth', type:'TC',
    text_india:'Which career appeals more?',
    text_usa:'Which career appeals more?',
    options_india:[{id:'A',text:'Generalist — broad, cross-functional, varied work'},{id:'B',text:'Specialist — deep expertise in one domain'}],
    options_usa:[{id:'A',text:'Generalist — broad, cross-functional, varied work'},{id:'B',text:'Specialist — deep expertise in one domain'}] },

  // ── SC×4 ───────────────────────────────────────────────────────
  { question_id:'D8-SC-001', dimension:'D8', facet:'Independent vs Collaborative', type:'SC',
    text_india:"You have a project to complete. You can do it alone with full freedom, or work closely with a strong team. Both will produce a good outcome. What do you choose?",
    text_usa:"You have an important project. You can do it alone with full freedom and ownership, or work closely with a talented team. Both will produce a good outcome. What do you choose?",
    options_india:[{id:'A',text:'Work alone — you always produce your best work independently'},{id:'B',text:'The team — collaboration improves the outcome and energises you'},{id:'C',text:'Depends entirely on who is in the team'},{id:'D',text:'Start alone, then bring others in for specific parts'}],
    options_usa:[{id:'A',text:'Work alone — your best work is always independent'},{id:'B',text:'The team — collaboration genuinely improves the outcome'},{id:'C',text:'Depends entirely on the people in the team'},{id:'D',text:'Start solo, bring others in for specific contributions'}] },
  { question_id:'D8-SC-002', dimension:'D8', facet:'Leading vs Executing', type:'SC',
    text_india:"Your team has no clear leader and is losing direction. What do you do?",
    text_usa:"Your team has no clear leader and is losing direction on an important project. What do you do?",
    options_india:[{id:'A',text:'Step up and take charge — someone has to'},{id:'B',text:'Suggest a process for the group to agree on direction'},{id:'C',text:'Focus on your own contribution and trust someone else will lead'},{id:'D',text:'Raise the issue but not necessarily lead the resolution'}],
    options_usa:[{id:'A',text:'Step up and take charge — someone has to do it'},{id:'B',text:'Suggest a structured process for the group to align'},{id:'C',text:'Focus on your own piece and trust someone else will step up'},{id:'D',text:'Raise the issue clearly without necessarily leading the solution'}] },
  { question_id:'D8-SC-003', dimension:'D8', facet:'Creating vs Implementing', type:'SC',
    text_india:"You have a choice of two projects. One is building something completely new — no template, no rulebook. One is taking an existing thing and making it excellent. Which do you choose?",
    text_usa:"Two projects available. One is building something completely new — blank canvas, no template. One is taking something good and making it truly excellent. Which do you choose?",
    options_india:[{id:'A',text:'The new build — creating from scratch excites you most'},{id:'B',text:'The excellence project — refining something is where you shine'},{id:'C',text:'Depends on the domain and what the outcome would be'},{id:'D',text:'You would want to do both phases — start it and perfect it'}],
    options_usa:[{id:'A',text:'The new build — creating from scratch is where you come alive'},{id:'B',text:'The excellence project — refining and perfecting is your strength'},{id:'C',text:'Depends on the domain and the stakes involved'},{id:'D',text:'You want both — you like to start it and then perfect it'}] },

  // ── CS×6 ───────────────────────────────────────────────────────
  { question_id:'D8-CS-001', dimension:'D8', facet:'Independent vs Collaborative', type:'CS',
    text_india:'When I do my absolute best work, I am usually...',
    text_usa:'When I do my absolute best work, the conditions are usually...' },
  { question_id:'D8-CS-002', dimension:'D8', facet:'Structured vs Flexible', type:'CS',
    text_india:'The work environment that brings out my best is...',
    text_usa:'The work environment that brings out the best in me is...' },
  { question_id:'D8-CS-003', dimension:'D8', facet:'Leading vs Executing', type:'CS',
    text_india:'In ten years, the role I want to be in looks like...',
    text_usa:'In ten years, the role I want to be playing looks like...' },
  { question_id:'D8-CS-004', dimension:'D8', facet:'Creating vs Implementing', type:'CS',
    text_india:'The kind of work that makes me feel most alive is...',
    text_usa:'The kind of work that makes me feel most fully alive is...' },
  { question_id:'D8-CS-005', dimension:'D8', facet:'Variety vs Depth', type:'CS',
    text_india:'What a genuinely good day of work feels like for me is...',
    text_usa:'What a genuinely great day of work looks and feels like for me is...' },
  { question_id:'D8-CS-006', dimension:'D8', facet:'Fast vs Deliberate', type:'CS',
    text_india:'The way I work that gets the best results — honestly — is...',
    text_usa:'The way I naturally work that consistently gets the best results is...' },
]

export default D8_QUESTIONS
